import assert from 'node:assert/strict';
import vm from 'node:vm';
import worker from '../src/index.js';
import {matchesSearch} from '../src/core.js';
const hit=path=>worker.fetch(new Request('https://tokyomedi.com'+path));
const html=async path=>(await hit(path)).text();
const itemLinks=(text,kind)=>[...new Set([...text.matchAll(new RegExp('href="(/zh-hans/'+kind+'/[^"?#]+)"','g'))].map(x=>x[1]))];
assert(matchesSearch('80mg EGFR inhibitor','ＥＧＦＲ 80 mg'));
assert(matchesSearch('Folate 400μg','400 µg'));
assert(!matchesSearch('EGFR 40mg','EGFR 80mg'));
let page=await html('/zh-hans/medicines?q=EGFR+80+mg&area=oncology&status=rx');
assert.deepEqual(itemLinks(page,'medicines'),['/zh-hans/medicines/osimertinib']);
assert(page.includes('name="area" value="oncology"')&&page.includes('name="status" value="rx"'));
assert(page.includes('href="/zh-hans/medicines?q=EGFR+80+mg&area=cardio&status=rx"><span>心血管</span><b>0</b>'));
assert(page.includes('href="/zh-hans/medicines?area=oncology&status=rx"'));
assert(page.includes('/ja/medicines?q=EGFR+80+mg&area=oncology&status=rx'));
page=await html('/zh-hans/health?q=维生素B12&kind=nutrient-food');
assert(itemLinks(page,'health').includes('/zh-hans/health/dhc-multivitamin'));
assert(itemLinks(page,'health').includes('/zh-hans/health/dhc-heme-iron'));
assert(page.includes('name="kind" value="nutrient-food"'));
assert(page.includes('/ja/health?q=%E7%BB%B4%E7%94%9F%E7%B4%A0B12&kind=nutrient-food'));
page=await html('/zh-hans/health/dhc-calcium-magnesium-20');
assert(page.includes('同配方其他包装')&&page.includes('/zh-hans/health/dhc-calcium-magnesium-60'));
assert(page.includes('class="breadcrumbs wrap"')&&page.includes('id="main-content"'));
assert(page.includes('打印 / 保存 PDF')&&page.includes('class="readingMenu" open'));
for(const slug of ['pembrolizumab','trastuzumab-deruxtecan','dupilumab','risankizumab'])assert(!(await html('/en/medicines/'+slug)).includes('#HDR_Interactions'));
page=await html('/ar/medicines/osimertinib');
assert(page.includes('id="main-content" tabindex="-1" lang="en" dir="ltr"')&&page.includes('Detailed reference content is available'));
assert(page.includes('<html lang="ar" dir="rtl">'));
for(const path of ['/zh-hans/about/extra','/en/travel/extra','/zh-hans/medicines/missing','/unknown']){
 const res=await hit(path);assert.equal(res.status,404,path);assert.equal(res.headers.get('x-robots-tag'),'noindex');assert((await res.text()).includes('class="skipLink"'));
}
const res=await worker.fetch(new Request('https://tokyomedi.com/en/inquiry',{method:'POST'}));assert.equal(res.status,405);assert.equal(res.headers.get('allow'),'GET, HEAD');
assert.equal((await worker.fetch(new Request('https://tokyomedi.com/',{headers:{'accept-language':'de-DE,de;q=0.9,en;q=0.8'}}))).headers.get('location'),'https://tokyomedi.com/de');
page=await html('/zh-hans/inquiry');
assert.equal([...page.matchAll(/<input[^>]+required/g)].length,4);
assert(page.includes('尚未发送')&&page.includes('复制邮件正文')&&page.includes('复制邮件正文'));
for(const script of page.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(script[1]);
// Verify exact values/newlines and escaped user input in the real generated browser script.
let submit,boxChildren=[],written;
const required=[{value:' Test Institute ',setCustomValidity(){}}];
const elements=[];
const box={replaceChildren(){boxChildren=[]},style:{},append(...children){boxChildren.push(...children)},focus(){},scrollIntoView(){}};
const form={querySelectorAll(){return required.map(x=>({...x,addEventListener(){}}))},addEventListener(type,fn){if(type==='submit')submit=fn},reportValidity(){return true}};
const createElement=tag=>{const el={tag,style:{},children:[],append(...children){this.children.push(...children)},setAttribute(){},addEventListener(type,fn){this[type]=fn},focus(){},select(){}};elements.push(el);return el};
const script=[...page.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(x=>x[1].includes('setupInquiry'))[1];
vm.runInNewContext(script,{document:{getElementById(id){return id==='inquiryForm'?form:box},createElement},FormData:class{get(k){return {f0:'Test Institute',f1:'Japan',f2:'<test product>',f3:'10'}[k]}},navigator:{clipboard:{async writeText(t){written=t}}},encodeURIComponent});
submit({preventDefault(){}});
const draft=elements.find(x=>x.tag==='textarea');assert(draft.value.includes('\n\n')&&!draft.value.includes('\\n'));assert(draft.value.includes('<test product>'));
const mail=elements.find(x=>x.tag==='a');assert(decodeURIComponent(mail.href.split('&body=')[1])===draft.value);
await elements.find(x=>x.tag==='button').click();assert.equal(written,draft.value);
assert(boxChildren.some(x=>x.tag==='p'&&x.textContent==='邮件正文已复制。'));
console.log('PASS: combined search, ingredient search, matched filter counts, retained filters, pack links, reading controls, locale disclosure, navigation, 404/405, inquiry validation and safe newline/copy generation');
