import {SITE,UI,strengths,medicines,guides,hospitals} from './data.js';
import {esc,p,labelArea,shell,medicineName,medicineRows,rxRows,guideTitle,guideExcerpt,jsonLd,breadcrumbLd,htmlLang} from './core.js';

export function home(l,req){const t=UI[l]; const lead=t.heroLead; const why=[
 ['01',l==='zh-hans'?'优先使用一手资料':l==='ja'?'一次資料を優先':'Primary sources first',l==='zh-hans'?'药品状态、医院受理等重要信息优先引用日本监管机构、厂家与医疗机构官方资料。':l==='ja'?'医薬品の状況や病院の受入条件など、重要な情報は規制当局・メーカー・医療機関の公式資料を優先します。':'Medicine status and hospital intake information are anchored to regulators, manufacturers and medical institutions.'],
 ['02',l==='zh-hans'?'医疗信息与交易分开':l==='ja'?'医療情報と取引を分離':'Medical information separated from commerce',l==='zh-hans'?'处方药页面用于查阅资料和理解医疗流程，不采用普通商品的购买路径。':l==='ja'?'処方薬ページは資料確認と医療手続きの理解を目的とし、一般商品の購入導線は設けません。':'Prescription pages support reference and care pathways rather than ordinary shopping flows.'],
 ['03',l==='zh-hans'?'按国际用户需求整理':l==='ja'?'海外利用者向けに整理':'Organized for international readers',l==='zh-hans'?'补充多语言名称、日本制度背景以及海外患者需要关注的医院受理条件。':l==='ja'?'多言語の名称、日本の制度背景、海外患者が確認すべき受入条件を整理します。':'Multilingual names, Japanese system context and overseas-patient intake requirements are organized together.'],
 ['04',l==='zh-hans'?'公开来源与核验日期':l==='ja'?'出典と確認日を表示':'Sources and verification dates shown',l==='zh-hans'?'区分官方文书更新时间与本站核验日期，便于判断资料的新旧与出处。':l==='ja'?'公式文書の更新日と当サイトの確認日を分け、情報の出典と時点を確認できるようにします。':'Official document dates and site verification dates are separated so readers can judge source and recency.']
 ];
 const trustProof=l==='zh-hans'?[
  ['PMDA','药品官方资料','日本商品名、厂家、规格与 PMDA 产品级资料逐条对应。'],
  ['HOSPITAL','医院官方信息','预约、转诊、协调机构与语言要求以医院官方页面为准。'],
  ['DATES','更新时间与核验日期','官方文书更新时间与 TOKYO MEDI 核验日期分别显示。'],
  ['BOUNDARY','医疗信息边界','不远程开处方，不把处方药按普通商品售卖。']
 ]:l==='ja'?[
  ['PMDA','医薬品の公式資料','日本販売名、製造販売元、規格を PMDA の製品別資料と照合。'],
  ['HOSPITAL','病院の公式情報','予約、紹介、コーディネーター、言語要件は病院公式情報で確認。'],
  ['DATES','更新日と確認日','公式文書の更新日と TOKYO MEDI の確認日を別々に表示。'],
  ['BOUNDARY','医療情報の範囲','遠隔で処方せず、処方薬を一般商品として販売しません。']
 ]:[
  ['PMDA','Official medicine sources','Japanese product names, manufacturers and strengths are matched to PMDA product-level records.'],
  ['HOSPITAL','Official hospital information','Appointments, referrals, coordinators and language requirements are checked against hospital sources.'],
  ['DATES','Document and verification dates','Official document dates and TOKYO MEDI verification dates are shown separately.'],
  ['BOUNDARY','Scope of medical information','No remote prescribing and no ordinary ecommerce flow for prescription medicines.']
 ];
 const japanEvidence=l==='zh-hans'?[
  ['2012','山中伸弥 · iPS 细胞','成熟细胞可被重新编程为多能状态，获得诺贝尔生理学或医学奖。','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','本庶佑 · 癌症免疫治疗','因通过抑制负性免疫调节实现癌症治疗的新原理，与 James P. Allison 共同获奖。','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','大村智 · 抗寄生虫治疗','其研究促成针对线虫寄生感染的新疗法，与 William C. Campbell 共同获奖。','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ]:l==='ja'?[
  ['2012','山中伸弥 · iPS細胞','成熟細胞を多能性状態へ再プログラムできる発見でノーベル生理学・医学賞。','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','本庶佑 · がん免疫療法','負の免疫制御の阻害によるがん治療の発見で James P. Allison と共同受賞。','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','大村智 · 抗寄生虫治療','線虫寄生感染に対する新規治療の発見で William C. Campbell と共同受賞。','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ]:[
  ['2012','Shinya Yamanaka · iPS cells','Awarded for the discovery that mature cells can be reprogrammed to become pluripotent.','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','Tasuku Honjo · cancer immunotherapy','Awarded jointly with James P. Allison for cancer therapy by inhibition of negative immune regulation.','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','Satoshi Ōmura · antiparasitic therapy','Awarded jointly with William C. Campbell for discoveries concerning a novel therapy against roundworm infections.','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ];
 const travelSteps=l==='zh-hans'?[['01','整理病历','准备诊断摘要、近期报告、影像和用药清单。'],['02','确认受理条件','核对转诊、协调机构、国际患者部门和预约要求。'],['03','准备必要翻译','按照接诊机构要求翻译关键资料。'],['04','确认预约与费用','出发前确认预约、收费、付款与后续资料衔接。']]:l==='ja'?[['01','診療情報を整理','診断サマリー、最近の報告、画像、服薬情報を準備。'],['02','受入条件を確認','紹介、コーディネーター、国際患者窓口、予約要件を確認。'],['03','必要資料を翻訳','受入先が求める主要資料を優先して翻訳。'],['04','予約と費用を確認','来日前に予約、費用、支払条件、帰国後の情報連携を確認。']]:[['01','Organize medical records','Prepare a diagnosis summary, recent reports, imaging and medication list.'],['02','Confirm intake requirements','Check referral, coordinator, international-patient and appointment requirements.'],['03','Translate required records','Translate the key documents requested by the receiving institution.'],['04','Confirm appointment and costs','Clarify appointment, billing, payment and follow-up information before travel.']];
 const body=`<main><section class="hero"><div class="wrap heroGrid"><div><div class="kicker">${esc(t.heroKicker)}</div><h1>${esc(t.heroTitle)}</h1><p class="lead">${esc(lead)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}" aria-label="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="heroMeta"><span><i></i>${l==='zh-hans'?'官方来源优先':l==='ja'?'一次資料を優先':'Primary sources first'}</span><span><i></i>${l==='zh-hans'?'三语信息结构':l==='ja'?'3言語構造':'Three-language structure'}</span><span><i></i>${l==='zh-hans'?'处方药无直接购买':l==='ja'?'処方薬の直接販売なし':'No direct Rx sales'}</span></div></div><div class="heroStage"><figure class="heroPhoto"><img src="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600" srcset="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=78&w=800 800w, https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600 1600w" sizes="(max-width:1080px) 100vw, 44vw" width="1600" height="1100" fetchpriority="high" decoding="async" alt="${l==='zh-hans'?'现代医学研究实验室':l==='ja'?'先端医療研究ラボ':'Modern medical research laboratory'}"><div class="heroPhotoVeil"></div><figcaption><span>JAPAN · RESEARCH · MEDICINE</span><strong>${l==='zh-hans'?'药品资料 · 医院受理 · 就医指南':l==='ja'?'医薬品資料 · 病院受入 · 受診ガイド':'Medicine reference · hospital intake · care guides'}</strong></figcaption></figure><div class="route"><div class="routeTitle">${esc(t.routeTitle)}</div>${t.routeItems.map((x,i)=>`<a class="routeRow" href="${p(l,x[0])}"><span class="routeNo">0${i+1}</span><div><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="sourceRail" aria-label="Primary medical sources"><div class="wrap sourceRailInner"><span class="sourceRailLead">${l==='zh-hans'?'主要核验来源':l==='ja'?'主な確認情報源':'Primary verification sources'}</span><div class="sourceRailMarks"><span><b>PMDA</b><small>Regulation / Safety</small></span><span><b>MHLW</b><small>Policy / Health system</small></span><span><b>RAD-AR</b><small>Patient medicine information</small></span></div></div></section>
 <section class="section proofSection" id="trust"><div class="wrap"><div class="sectionHead compactHead"><div><div class="eyebrow">01 · SOURCES & VERIFICATION</div><h2>${l==='zh-hans'?'资料来源与核验':l==='ja'?'情報源と確認':'Sources and verification'}</h2></div><p>${l==='zh-hans'?'药品与赴日医疗信息均标明来源、核验日期和适用范围。':l==='ja'?'医薬品と医療渡航情報について、情報源、確認日、適用範囲を明示します。':'Medicine and medical-travel information is presented with sources, verification dates and scope.'}</p></div><div class="proofGrid">${trustProof.map(x=>`<div class="proofItem"><span>${esc(x[0])}</span><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div>`).join('')}</div></div></section>
 <section class="section strength evidenceSection" id="strength"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">02 · MEDICAL RESEARCH IN JAPAN</div><h2>${esc(t.strength)}</h2></div><p>${esc(t.strengthLead)}</p></div><div class="evidenceList">${japanEvidence.map(x=>`<a class="evidenceRow" href="${x[3]}" target="_blank" rel="noopener"><span class="evidenceYear">${esc(x[0])}</span><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div><b>NOBEL PRIZE ↗</b></a>`).join('')}</div></div></section>
 <section class="section database" id="database"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">03 · MEDICINE DATABASE</div><h2>${esc(t.medicineDb)}</h2></div><p>${esc(t.medicineLead)}</p></div><div class="dbPanel"><div class="dbSearch"><h3>${esc(t.search)}</h3><p>${esc(t.noBuy)}</p><div class="dbProof"><span><b>${medicines.length}</b>${l==='zh-hans'?'条产品级核验记录':l==='ja'?'件の製品別確認記録':'product-level verified records'}</span><span><b>PMDA</b>${l==='zh-hans'?'产品级一手来源':l==='ja'?'製品別一次資料':'product-level primary sources'}</span></div><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="chips">${Object.entries(t.filters).map(([k,v])=>`<a class="chip" href="${p(l,'medicines')}?area=${k==='all'?'':k}">${esc(v)}</a>`).join('')}</div></div><div class="medicineRows">${medicineRows(l,medicines,7)}</div></div></div></section>
 <section class="section trustSection"><div class="wrap trustLayout"><div class="trustStatement"><div class="eyebrow">04 · EDITORIAL POLICY</div><h2>${esc(t.why)}</h2><p>${l==='zh-hans'?'药品资料按产品级官方来源整理；赴日医疗内容仅提供医院官方受理信息与制度资料。TOKYO MEDI 不提供个人医疗咨询、挂号、诊断、处方或就医协调。':l==='ja'?'医薬品情報は製品別の公式資料を基準に整理し、医療渡航情報は病院公式の受入情報と制度資料に限定します。TOKYO MEDI は個人向けの医療相談、予約、診断、処方、受診調整を行いません。':'Medicine records are organized from product-level official sources. Medical-travel content is limited to official hospital intake and system information. TOKYO MEDI does not provide personal medical consultation, appointments, diagnosis, prescribing or care coordination.'}</p><a class="textLink" href="${p(l,'sources')}">${esc(t.official)} →</a></div><div class="whyStack">${why.map(x=>`<div class="whyItem"><span>${x[0]}</span><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div></div>`).join('')}</div></div></section>
 <section class="section guides" id="guides"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">05 · MEDICAL GUIDES</div><h2>${esc(t.guides)}</h2></div><a class="textLink" href="${p(l,'guides')}">${esc(t.viewAll)} →</a></div><div class="guideLayout"><a class="featuredGuide" href="${p(l,'guides/'+guides[0].slug)}"><div><div class="eyebrow">FEATURED · ${guides[0].date}</div><h3>${esc(guideTitle(l,guides[0]))}</h3><p>${esc(guideExcerpt(l,guides[0]))}</p></div><span class="textLink">${esc(t.read)} →</span></a><div class="guideList">${guides.slice(1).map(g=>`<a class="guideRow" href="${p(l,'guides/'+g.slug)}"><div><h3>${esc(guideTitle(l,g))}</h3><p>${esc(guideExcerpt(l,g))}</p></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="section" id="travel"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">06 · MEDICAL TRAVEL INFORMATION</div><h2>${esc(t.travel)}</h2></div><a class="textLink" href="${p(l,'travel')}">${esc(t.viewAll)} →</a></div><div class="travelGrid"><div class="travelVisual"><img src="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600" srcset="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=76&w=800 800w, https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600 1600w" sizes="(max-width:1080px) 100vw, 42vw" width="1600" height="1050" loading="lazy" decoding="async" alt="Tokyo"><div class="travelVisualCopy"><span>TOKYO / JAPAN</span><strong>${l==='zh-hans'?'先确认医疗需求、医院受理条件和预约方式，再安排就诊。':l==='ja'?'医療ニーズ、病院の受入条件、予約方法を確認してから受診を準備します。':'Confirm the medical need, hospital intake requirements and appointment route before arranging care.'}</strong></div></div><div class="travelFlow"><div class="timeline">${travelSteps.map(s=>`<div class="step"><strong>${esc(s[0])} · ${esc(s[1])}</strong><p>${esc(s[2])}</p></div>`).join('')}</div><div class="hospitalPreview">${hospitals.slice(0,5).map(h=>`<a class="hospitalRow" href="${p(l,'travel')}#${h.slug}"><div><strong>${esc(h.name)}</strong><small>${esc(h.ja)} · ${esc(h.path)}</small></div><span>${esc(h.city)}</span><b>→</b></a>`).join('')}</div></div></div></div></section>
 <section class="section institutionInquiry" id="institutional-inquiry"><div class="wrap institutionInquiryGrid"><div><div class="eyebrow">07 · INSTITUTIONAL INQUIRY</div><h2>${l==='zh-hans'?'医药品询价说明':l==='ja'?'機関向け医薬品照会':'Institutional medicine inquiry'}</h2><p>${l==='zh-hans'?'仅面向医疗机构、药局与企业。询价时请提供机构信息、药品名称与规格、数量、目的地及相关资质。本站不接受个人处方药购买请求，也不提供个人医疗咨询。':l==='ja'?'医療機関・薬局・企業のみを対象とします。機関情報、医薬品名・規格、数量、仕向地、関連資格情報をご提示ください。個人からの処方薬購入依頼や医療相談は受け付けていません。':'For institutions, pharmacies and companies only. Please provide institution details, medicine and strength, quantity, destination and relevant credentials. Personal prescription-medicine purchase requests and medical consultations are not accepted.'}</p></div><div class="institutionInquiryMeta"><span><b>${l==='zh-hans'?'对象':l==='ja'?'対象':'For'}</b>${l==='zh-hans'?'医疗机构 / 药局 / 企业':l==='ja'?'医療機関 / 薬局 / 企業':'Institutions / pharmacies / companies'}</span><span><b>${l==='zh-hans'?'需要':l==='ja'?'必要情報':'Required'}</b>${l==='zh-hans'?'品项 / 规格 / 数量 / 目的地 / 资质':l==='ja'?'品目 / 規格 / 数量 / 仕向地 / 資格情報':'Item / strength / quantity / destination / credentials'}</span><a class="btn teal" href="${p(l,'inquiry')}?type=institution">${esc(t.startInstitution)}</a></div></div></section>
 <section class="section rxShowcase" id="prescription"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">08 · PRESCRIPTION REFERENCE</div><h2>${esc(t.rx)}</h2></div><a class="textLink" href="${p(l,'medicines')}?status=rx">${esc(t.viewAll)} →</a></div><div class="rxTable">${rxRows(l,medicines,8)}</div><div class="rxNext"><div><span class="eyebrow">PRESCRIPTION MEDICINE</span><strong>${l==='zh-hans'?'处方药页面仅提供产品与官方资料。是否适用、是否开具以及如何使用，由医生和药师根据实际情况判断。':l==='ja'?'処方薬ページは製品情報と公式資料のみを提供します。適否、処方、使用方法は医師・薬剤師が個別に判断します。':'Prescription pages provide product and primary-source information only. Suitability, prescribing and use are determined by clinicians and pharmacists.'}</strong></div><a class="btn teal" href="${p(l,'medicines')}">${l==='zh-hans'?'查看全部药品资料':l==='ja'?'医薬品資料を見る':'Browse medicine reference'} →</a></div></div></section>
</main>`;
 const homeTitle=l==='zh-hans'?'日本医药品资料库与赴日医疗':l==='ja'?'日本医薬品リファレンスと医療渡航':'Japanese Medicine Reference & Medical Travel';
 return shell(l,req,homeTitle,lead,'',body);
}

export function medicinesPage(l,req){const t=UI[l],u=new URL(req.url),rawQ=(u.searchParams.get('q')||'').trim(),q=rawQ.toLowerCase(),area=(u.searchParams.get('area')||'').trim(); let items=medicines.filter(m=>!area||m.area===area); if(q)items=items.filter(m=>[m.en,m.ja,m.zh,m.slug,m.area,m.productJa,m.brandEn,m.manufacturerJa,m.strengths,...(m.alternateProductsJa||[])].filter(Boolean).join(' ').toLowerCase().includes(q));
 const intro=l==='zh-hans'?'查询日本商品名、一般名、品牌、制造销售企业、规格与 PMDA 官方资料。处方药仅作资料展示，不提供在线购药。':l==='ja'?'日本販売名、一般名、ブランド、製造販売元、規格、PMDA公式資料を検索できます。処方薬は資料表示のみで、オンライン販売は行いません。':'Search Japanese product names, generics, brands, marketing authorization holders, strengths and PMDA primary sources. Prescription medicines are reference-only and are not sold online.';
 const latestVerified=medicines.map(m=>m.verifiedAt).filter(Boolean).sort().at(-1)||'—';
 const label=(key)=>l==='zh-hans'?({manufacturer:'制造销售企业',strengths:'规格 / 含量',form:'剂型',verified:'本站核验',view:'查看完整资料',records:'产品级核验记录',sources:'PMDA 产品级来源',scope:'处方药资料边界',results:'条资料',all:'全部药品'}[key]||key):l==='ja'?({manufacturer:'製造販売元',strengths:'規格 / 含量',form:'剤形',verified:'当サイト確認',view:'詳細資料を見る',records:'製品別確認記録',sources:'PMDA 製品別一次資料',scope:'処方薬情報の範囲',results:'件',all:'すべて'}[key]||key):({manufacturer:'Marketing authorization holder',strengths:'Strengths',form:'Dosage form',verified:'Site verified',view:'View full reference',records:'product-level verified records',sources:'PMDA product-level sources',scope:'Prescription reference boundary',results:'records',all:'All medicines'}[key]||key);
 const cards=items.map(m=>{const primary=l==='zh-hans'?m.zh:l==='ja'?m.productJa:(m.brandEn||m.en); const secondary=l==='zh-hans'?[m.brandEn,m.productJa].filter(Boolean).join(' · '):l==='ja'?[m.en,m.brandEn].filter(Boolean).join(' · '):[m.en,m.productJa].filter(Boolean).join(' · '); return `<a class="medicineCard" data-area="${esc(m.area)}" href="${p(l,'medicines/'+m.slug)}"><div class="medicineCardTop"><span class="medicineArea">${esc(labelArea(l,m.area))}</span><span class="medicineStatus">${esc(m.status)}</span></div><h2>${esc(primary)}</h2><p class="medicineCardNames">${esc(secondary)}</p><div class="medicineCardFacts"><div><span>${esc(label('manufacturer'))}</span><strong>${esc(m.manufacturerJa)}</strong></div><div><span>${esc(label('strengths'))}</span><strong>${esc(m.strengths)}</strong></div><div><span>${esc(label('form'))}</span><strong>${esc(m.form)}</strong></div><div><span>${esc(label('verified'))}</span><strong>${esc(m.verifiedAt)}</strong></div></div><div class="medicineCardFoot"><span class="pmdaVerified"><i></i>PMDA</span><b>${esc(label('view'))} →</b></div></a>`;}).join('');
 const filterLinks=Object.entries(t.filters).map(([k,v])=>{const val=k==='all'?'':k,count=k==='all'?medicines.length:medicines.filter(m=>m.area===k).length,qs=new URLSearchParams();if(rawQ)qs.set('q',rawQ);if(val)qs.set('area',val);return `<a class="filter ${area===val?'on':''}" href="${p(l,'medicines')}?${qs}"><span>${esc(v)}</span><b>${count}</b></a>`;}).join('');
 const empty=l==='zh-hans'?'没有找到匹配资料。可尝试一般名、品牌名、日本商品名或制造销售企业。':l==='ja'?'一致する資料がありません。一般名、ブランド名、日本販売名、製造販売元をお試しください。':'No matching records. Try a generic name, brand, Japanese product name or marketing authorization holder.';
 const body=`<main class="medicineIndex"><section class="medicineIndexHero"><div class="wrap medicineIndexHeroGrid"><div class="medicineIndexIntro"><div class="eyebrow">JAPAN MEDICINE REFERENCE</div><h1>${esc(t.nav.medicines)}</h1><p>${esc(intro)}</p><form class="medicineSearch" action="${p(l,'medicines')}" method="get"><input name="q" value="${esc(rawQ)}" placeholder="${esc(t.searchPlaceholder)}" aria-label="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form></div><aside class="medicineIndexTrust"><div><span>PMDA</span><strong>${esc(label('sources'))}</strong></div><div><span>${medicines.length}</span><strong>${esc(label('records'))}</strong></div><div><span>${esc(latestVerified)}</span><strong>${esc(label('verified'))}</strong></div><p>${l==='zh-hans'?'产品信息用于资料查询。实际适用、处方和使用方式须由医生或药师根据具体情况判断。':l==='ja'?'製品情報は資料確認のためのものです。適否、処方、使用方法は医師・薬剤師が個別に判断します。':'Product information is provided for reference. Suitability, prescribing and use are determined by clinicians and pharmacists.'}</p></aside></div></section><section class="medicineIndexBody"><div class="wrap"><div class="medicineToolbar"><div><span class="medicineResultCount"><b>${items.length}</b> ${esc(label('results'))}</span>${rawQ?`<span class="medicineQuery">“${esc(rawQ)}”</span>`:''}</div><div class="medicineFilterLabel">${l==='zh-hans'?'按治疗领域筛选':l==='ja'?'領域で絞り込む':'Filter by therapeutic area'}</div></div><div class="medicineFilters">${filterLinks}</div>${items.length?`<div class="medicineCardGrid">${cards}</div>`:`<div class="medicineEmpty"><strong>${esc(empty)}</strong><a href="${p(l,'medicines')}">${esc(label('all'))} →</a></div>`}<div class="medicineIndexNote"><div><span>PMDA</span><strong>${l==='zh-hans'?'官方资料优先':l==='ja'?'一次資料を優先':'Primary sources first'}</strong></div><p>${l==='zh-hans'?'批准状态、添付文书、安全性信息和最新修订内容，以 PMDA 等日本官方来源为准。TOKYO MEDI 显示的是资料索引与核验信息，不替代官方文书。':l==='ja'?'承認状況、添付文書、安全性情報、最新の改訂内容は PMDA 等の公式情報をご確認ください。TOKYO MEDI は資料索引と確認情報を提供し、公式文書に代わるものではありません。':'Approval status, labels, safety information and current revisions should be confirmed in official Japanese sources such as PMDA. TOKYO MEDI provides a reference index and verification context, not a replacement for official documents.'}</p><a href="https://www.pmda.go.jp/PmdaSearch/iyakuSearch/" target="_blank" rel="noopener">PMDA ↗</a></div></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:t.nav.medicines,description:intro,url:SITE+p(l,'medicines'),inLanguage:htmlLang(l),mainEntity:{'@type':'ItemList',itemListElement:items.map((m,i)=>({'@type':'ListItem',position:i+1,name:l==='zh-hans'?m.zh:(l==='ja'?m.productJa:(m.brandEn||m.en)),url:SITE+p(l,'medicines/'+m.slug)}))}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.medicines,p(l,'medicines')]]);
 return shell(l,req,t.nav.medicines,intro,'medicines',body,ld);
}

export function medicineDetail(l,req,slug){const t=UI[l],m=medicines.find(x=>x.slug===slug); if(!m)return null;
 const scopeNote=m.scope==='representative'?(l==='zh-hans'?'本页以日本市场中的代表性产品作为资料入口；同一成分可能存在其他产品或剂型。':l==='ja'?'本ページは日本での代表的な製品を資料入口としており、同一成分に他の製品・剤形が存在する場合があります。':'This page uses a representative Japanese product as the reference entry; other products or dosage forms may exist for the same ingredient.'):'';
 const statusNote=l==='zh-hans'?m.statusNoteZh:l==='ja'?m.statusNoteJa:m.statusNoteEn;
 const desc=l==='zh-hans'?`${m.productJa}｜${m.zh}（${m.en}）官方资料索引。${scopeNote}`:l==='ja'?`${m.productJa}｜${m.en} の公式資料リファレンス。${scopeNote}`:`${m.brandEn||m.productJa} / ${m.en}: verified Japanese product reference. ${scopeNote}`;
 const fields=l==='zh-hans'?[
   ['日本商品名',m.productJa],['品牌',m.brandEn],['中文名',m.zh],['英文一般名',m.en],['日文一般名',m.ja],['制造销售企业',m.manufacturerJa],['规格 / 含量',m.strengths],['剂型',m.form],['治疗领域',labelArea(l,m.area)],['监管属性',m.status],['添付文书更新',m.labelUpdated],['TOKYO MEDI 核验',m.verifiedAt]
 ]:l==='ja'?[
   ['日本販売名',m.productJa],['ブランド',m.brandEn],['一般名（日本語）',m.ja],['一般名（英語）',m.en],['中国語名',m.zh],['製造販売元',m.manufacturerJa],['規格',m.strengths],['剤形',m.form],['領域',labelArea(l,m.area)],['区分',m.status],['添付文書更新',m.labelUpdated],['TOKYO MEDI 確認日',m.verifiedAt]
 ]:[
   ['Japan product name',m.productJa],['Brand',m.brandEn],['Generic name',m.en],['Japanese generic name',m.ja],['Chinese name',m.zh],['Marketing authorization holder',m.manufacturerJa],['Strengths',m.strengths],['Dosage form',m.form],['Therapeutic area',labelArea(l,m.area)],['Regulatory status',m.status],['Label updated',m.labelUpdated],['TOKYO MEDI verified',m.verifiedAt]
 ];
 const alternates=(m.alternateProductsJa||[]).length?`<div class="sourceBox altProducts"><strong>${l==='zh-hans'?'同成分的其他日本商品':l==='ja'?'同一成分の他製品':'Other Japanese products with the same ingredient'}</strong><p>${esc(m.alternateProductsJa.join(' · '))}</p><p>${esc(scopeNote)}</p></div>`:'';
 const body=`<main><section class="pageHero medicineHero"><div class="wrap"><div class="eyebrow">${esc(m.status)} · ${esc(t.noBuy)}</div><h1>${esc(medicineName(l,m))}</h1><p>${esc(desc)}</p><div class="verificationStrip"><span><b>PMDA</b>${l==='zh-hans'?'产品级来源':l==='ja'?'製品別一次資料':'product-level source'}</span><span><b>${esc(m.labelUpdated)}</b>${l==='zh-hans'?'添付文书更新':l==='ja'?'添付文書更新':'label updated'}</span><span><b>${esc(m.verifiedAt)}</b>${l==='zh-hans'?'本站核验':l==='ja'?'当サイト確認':'site verified'}</span></div></div></section><section class="content"><div class="wrap detailGrid"><div><dl class="factList">${fields.map(f=>`<div class="fact"><dt>${esc(f[0])}</dt><dd>${esc(f[1]||'—')}</dd></div>`).join('')}</dl>${statusNote?`<div class="statusNote"><strong>${l==='zh-hans'?'监管状态说明':l==='ja'?'区分に関する注記':'Regulatory status note'}</strong><p>${esc(statusNote)}</p></div>`:''}${alternates}<div class="sourceBox sourceActions"><strong>${esc(t.official)}</strong><p>${l==='zh-hans'?'以下链接直接进入该日本品项的 PMDA 官方资料。患者向页面与医疗专业人员页面分开提供。':l==='ja'?'以下はこの製品のPMDA公式資料です。一般向け情報と医療関係者向け情報を分けて案内します。':'These links go directly to PMDA records for this Japanese product. Professional and patient-facing sources are separated.'}</p><div class="sourceButtons"><a class="btn teal" href="${m.source}" target="_blank" rel="noopener">PMDA · ${l==='zh-hans'?'专业资料':l==='ja'?'医療関係者向け':'professional'} ↗</a>${m.patientSource?`<a class="btn ghost" href="${m.patientSource}" target="_blank" rel="noopener">PMDA · ${l==='zh-hans'?'患者资料':l==='ja'?'一般向け':'patient'} ↗</a>`:''}</div></div></div><aside class="sideNote"><strong>${esc(m.status)} · ${esc(t.noBuy)}</strong><p>${esc(t.rxNotice)}</p><div class="sideVerify"><span>${l==='zh-hans'?'来源':'Source'}<b>PMDA</b></span><span>${l==='zh-hans'?'核验':'Verified'}<b>${esc(m.verifiedAt)}</b></span></div><a class="btn teal" href="${p(l,'travel')}">${esc(t.startPersonal)}</a><a class="textLink sideInstitution" href="${p(l,'inquiry')}?medicine=${encodeURIComponent(m.productJa)}&type=institution">${l==='zh-hans'?'机构询价':l==='ja'?'機関向け照会':'Institutional inquiry'} →</a></aside></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'MedicalWebPage',name:medicineName(l,m),description:desc,dateModified:m.verifiedAt,url:SITE+p(l,'medicines/'+m.slug),inLanguage:htmlLang(l),publisher:{'@id':SITE+'/#organization'},isPartOf:{'@id':SITE+'/#website'},about:{'@type':'Drug',name:m.en,alternateName:[m.productJa,m.brandEn,m.ja,m.zh].filter(Boolean),nonProprietaryName:m.en,proprietaryName:m.brandEn||undefined,activeIngredient:m.en,dosageForm:m.form,manufacturer:{'@type':'Organization',name:m.manufacturerJa},sameAs:m.source,...(m.status==='Rx'?{prescriptionStatus:'https://schema.org/PrescriptionOnly'}:{})}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.medicines,p(l,'medicines')],[medicineName(l,m),p(l,'medicines/'+m.slug)]]);
 return shell(l,req,medicineName(l,m),desc,'medicines',body,ld);
}
