import {SITE,UI,strengths,medicines,guides,hospitals} from './data.js';
import {esc,p,labelArea,shell,medicineName,medicineRows,rxRows,guideTitle,guideExcerpt,jsonLd} from './core.js';

export function home(l,req){const t=UI[l]; const lead=t.heroLead; const why=[
 ['01',l==='zh-hans'?'官方来源优先':l==='ja'?'一次資料を優先':'Primary sources first',l==='zh-hans'?'重要事实尽量回到日本官方、厂家和医疗机构公开资料。':l==='ja'?'重要な事実は日本の公的機関、メーカー、医療機関の公開情報に戻ります。':'Important facts lead back to Japanese authorities, manufacturers and medical institutions.'],
 ['02',l==='zh-hans'?'医疗与商业分离':l==='ja'?'医療と商取引を分離':'Medical and commercial paths separated',l==='zh-hans'?'处方药不套普通商品购买逻辑。':l==='ja'?'処方薬を一般商品の購入導線に載せません。':'Prescription medicine does not use an ordinary shopping flow.'],
 ['03',l==='zh-hans'?'面向国际用户重组':l==='ja'?'海外利用者向けに再構成':'Built for international readers',l==='zh-hans'?'补充不同语言名称、制度背景和国际患者受理条件。':l==='ja'?'多言語名、制度背景、海外患者の受入条件を補足します。':'Add multilingual names, system context and overseas-patient intake requirements.'],
 ['04',l==='zh-hans'?'显示核验状态':l==='ja'?'確認状況を表示':'Verification status shown',l==='zh-hans'?'来源和核验日期直接显示，不把旧资料伪装成最新信息。':l==='ja'?'出典と確認日を示し、古い情報を最新として扱いません。':'Sources and verification dates are visible rather than presenting stale material as current.']
 ];
 const travelSteps=l==='zh-hans'?[['01','准备病历','整理诊断、近期报告、影像和用药清单。'],['02','确认受理方式','先看医院是否要求协调机构、转诊或国际患者部门。'],['03','准备翻译','只翻译接诊机构真正需要的材料。'],['04','确认费用与随访','在出发前确认收费方式、付款要求和回国后资料衔接。']]:l==='ja'?[['01','診療情報を準備','診断、最近の報告、画像、服薬情報を整理。'],['02','受入経路を確認','コーディネーター、紹介元、国際患者部門の要否を確認。'],['03','翻訳を準備','受入先が必要とする資料を優先して翻訳。'],['04','費用とフォロー','費用、支払条件、帰国後の連携を確認。']]:[['01','Prepare records','Organize diagnosis, recent reports, imaging and medication list.'],['02','Confirm intake route','Check whether a coordinator, referral or international office is required.'],['03','Prepare translation','Translate what the receiving institution actually needs.'],['04','Confirm cost & follow-up','Clarify billing, payment and post-return continuity before travel.']];
 const body=`<main><section class="hero"><div class="wrap heroGrid"><div><div class="kicker">${esc(t.heroKicker)}</div><h1>${esc(t.heroTitle)}</h1><p class="lead">${esc(lead)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}" aria-label="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="heroMeta"><span><i></i>${l==='zh-hans'?'官方来源优先':l==='ja'?'一次資料を優先':'Primary sources first'}</span><span><i></i>${l==='zh-hans'?'三语信息结构':l==='ja'?'3言語構造':'Three-language structure'}</span><span><i></i>${l==='zh-hans'?'处方药无直接购买':l==='ja'?'処方薬の直接販売なし':'No direct Rx sales'}</span></div></div><div class="heroStage"><figure class="heroPhoto"><img src="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600" srcset="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=78&w=800 800w, https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600 1600w" sizes="(max-width:1080px) 100vw, 44vw" width="1600" height="1100" fetchpriority="high" decoding="async" alt="${l==='zh-hans'?'现代医学研究实验室':l==='ja'?'先端医療研究ラボ':'Modern medical research laboratory'}"><div class="heroPhotoVeil"></div><figcaption><span>JAPAN · RESEARCH · MEDICINE</span><strong>${l==='zh-hans'?'从原始资料到下一步医疗路径':l==='ja'?'一次資料から次の医療経路へ':'From primary sources to the next care pathway'}</strong></figcaption></figure><div class="route"><div class="routeTitle">${esc(t.routeTitle)}</div>${t.routeItems.map((x,i)=>`<a class="routeRow" href="${p(l,x[0])}"><span class="routeNo">0${i+1}</span><div><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="sourceRail" aria-label="Primary medical sources"><div class="wrap sourceRailInner"><span class="sourceRailLead">${l==='zh-hans'?'资料核验优先回到日本一手来源':l==='ja'?'検証は日本の一次情報を優先':'Verification starts with Japanese primary sources'}</span><div class="sourceRailMarks"><span><b>PMDA</b><small>Regulation / Safety</small></span><span><b>MHLW</b><small>Policy / Health system</small></span><span><b>RAD-AR</b><small>Patient medicine information</small></span></div></div></section>
 <section class="section strength" id="strength"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">01 · JAPAN MEDICINE</div><h2>${esc(t.strength)}</h2></div><p>${esc(t.strengthLead)}</p></div><div class="strengthMedia"><figure class="strengthPhoto"><img src="https://images.unsplash.com/photo-1631556760585-2e846196d5a9?auto=format&fit=crop&q=80&w=1400" srcset="https://images.unsplash.com/photo-1631556760585-2e846196d5a9?auto=format&fit=crop&q=76&w=700 700w, https://images.unsplash.com/photo-1631556760585-2e846196d5a9?auto=format&fit=crop&q=80&w=1400 1400w" sizes="(max-width:760px) 100vw, 58vw" width="1400" height="900" loading="lazy" decoding="async" alt="${l==='zh-hans'?'医学研究人员使用显微镜':l==='ja'?'顕微鏡を使う医療研究者':'Medical researcher using a microscope'}"></figure><div class="strengthManifesto"><span class="manifestoNo">04</span><div><div class="eyebrow">${l==='zh-hans'?'四个判断维度':l==='ja'?'4つの評価軸':'FOUR LENSES'}</div><strong>${l==='zh-hans'?'不是宣传日本医疗，而是拆开监管、科研、临床与可追溯性。':l==='ja'?'日本医療を宣伝するのではなく、規制・研究・臨床・追跡可能性に分けて理解します。':'Not a slogan about Japan — a structured view of regulation, research, clinical care and traceability.'}</strong></div></div></div><div class="strengthList">${strengths.map((s,i)=>`<div class="strengthRow"><span>0${i+1}</span><h3>${esc(s.title[l]||s.title.en)}</h3><p>${esc(s.body[l]||s.body.en)}</p></div>`).join('')}</div></div></section>
 <section class="section database" id="database"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">02 · MEDICINE DATABASE</div><h2>${esc(t.medicineDb)}</h2></div><p>${esc(t.medicineLead)}</p></div><div class="dbPanel"><div class="dbSearch"><h3>${esc(t.search)}</h3><p>${esc(t.noBuy)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="chips">${Object.entries(t.filters).map(([k,v])=>`<a class="chip" href="${p(l,'medicines')}?area=${k==='all'?'':k}">${esc(v)}</a>`).join('')}</div></div><div class="medicineRows">${medicineRows(l,medicines,7)}</div></div></div></section>
 <section class="section trustSection"><div class="wrap trustLayout"><div class="trustStatement"><div class="eyebrow">03 · METHOD</div><h2>${esc(t.why)}</h2><p>${l==='zh-hans'?'TOKYO MEDI 的价值不是“内容更多”，而是把来源、医疗边界、国际用户语境和下一步行动放在同一个信息结构里。':l==='ja'?'TOKYO MEDIの価値は情報量ではなく、出典、医療上の境界、海外利用者の文脈、次の行動を一つの構造にまとめることです。':'TOKYO MEDI is not about having more content. It connects sources, medical boundaries, international context and the next action in one information structure.'}</p><a class="textLink" href="${p(l,'sources')}">${esc(t.official)} →</a></div><div class="whyStack">${why.map(x=>`<div class="whyItem"><span>${x[0]}</span><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div></div>`).join('')}</div></div></section>
 <section class="section guides" id="guides"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">04 · GUIDES</div><h2>${esc(t.guides)}</h2></div><a class="textLink" href="${p(l,'guides')}">${esc(t.viewAll)} →</a></div><div class="guideLayout"><a class="featuredGuide" href="${p(l,'guides/'+guides[0].slug)}"><div><div class="eyebrow">FEATURED · ${guides[0].date}</div><h3>${esc(guideTitle(l,guides[0]))}</h3><p>${esc(guideExcerpt(l,guides[0]))}</p></div><span class="textLink">${esc(t.read)} →</span></a><div class="guideList">${guides.slice(1).map(g=>`<a class="guideRow" href="${p(l,'guides/'+g.slug)}"><div><h3>${esc(guideTitle(l,g))}</h3><p>${esc(guideExcerpt(l,g))}</p></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="section" id="travel"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">05 · MEDICAL TRAVEL</div><h2>${esc(t.travel)}</h2></div><a class="textLink" href="${p(l,'travel')}">${esc(t.viewAll)} →</a></div><div class="travelGrid"><div class="travelVisual"><img src="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600" srcset="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=76&w=800 800w, https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600 1600w" sizes="(max-width:1080px) 100vw, 42vw" width="1600" height="1050" loading="lazy" decoding="async" alt="Tokyo"><div class="travelVisualCopy"><span>TOKYO / JAPAN</span><strong>${l==='zh-hans'?'不是先选医院，而是先确认医疗需求与受理路径。':l==='ja'?'病院選びの前に、医療ニーズと受入経路を確認します。':'Start with the medical need and intake route — not a random hospital list.'}</strong></div></div><div class="travelFlow"><div class="timeline">${travelSteps.map(s=>`<div class="step"><strong>${esc(s[0])} · ${esc(s[1])}</strong><p>${esc(s[2])}</p></div>`).join('')}</div><div class="hospitalPreview">${hospitals.slice(0,5).map(h=>`<a class="hospitalRow" href="${p(l,'travel')}#${h.slug}"><div><strong>${esc(h.name)}</strong><small>${esc(h.ja)} · ${esc(h.path)}</small></div><span>${esc(h.city)}</span><b>→</b></a>`).join('')}</div></div></div></div></section>
 <section class="section inquirySection" id="inquiry"><div class="wrap"><div class="sectionHead inquiryHead"><div><div class="eyebrow">06 · NEXT STEP</div><h2>${esc(t.inquiry)}</h2></div><p>${l==='zh-hans'?'先判断你是谁，再决定信息需要走向医疗咨询还是机构询价。两条路径从这里开始分开。':l==='ja'?'まず利用者の立場を確認し、医療相談と機関照会の経路をここで分けます。':'Identify who you are first. Patient guidance and institutional sourcing split into two different paths here.'}</p></div><div class="decisionRail"><span>01 ${l==='zh-hans'?'查资料':l==='ja'?'資料確認':'REFERENCE'}</span><i></i><span>02 ${l==='zh-hans'?'判断路径':l==='ja'?'経路判断':'ROUTE'}</span><i></i><span>03 ${l==='zh-hans'?'咨询/询价':l==='ja'?'相談・照会':'ACTION'}</span></div><div class="inquirySplit"><div class="inquiryCard"><div class="eyebrow">A · PATIENT / INDIVIDUAL</div><h3>${esc(t.personal)}</h3><p>${esc(t.personalDesc)}</p><ul><li>${l==='zh-hans'?'确认药品名称与处方属性':l==='ja'?'医薬品名と処方区分を確認':'Confirm medicine identity and prescription status'}</li><li>${l==='zh-hans'?'了解需要医生/药师参与的环节':l==='ja'?'医師・薬剤師が必要な段階を確認':'Understand where a doctor/pharmacist is required'}</li><li>${l==='zh-hans'?'需要时进入赴日医疗路径':l==='ja'?'必要に応じて医療渡航へ':'Move into a medical-travel pathway if needed'}</li></ul><a class="btn teal" href="${p(l,'inquiry')}?type=personal">${esc(t.startPersonal)}</a></div><div class="inquiryCard"><div class="eyebrow">B · INSTITUTIONAL</div><h3>${esc(t.institution)}</h3><p>${esc(t.institutionDesc)}</p><ul><li>${l==='zh-hans'?'机构名称与国家/地区':l==='ja'?'機関名と国・地域':'Institution and country/region'}</li><li>${l==='zh-hans'?'药品、规格、数量与目的地':l==='ja'?'医薬品、規格、数量、仕向地':'Medicine, specification, quantity and destination'}</li><li>${l==='zh-hans'?'许可证或资质信息':l==='ja'?'許可・資格情報':'Licence or credential information'}</li></ul><a class="btn" href="${p(l,'inquiry')}?type=institution">${esc(t.startInstitution)}</a></div></div><div class="rxNote">${esc(t.rxNotice)}</div></div></section>
 <section class="section rxShowcase" id="prescription"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">07 · PRESCRIPTION REFERENCE</div><h2>${esc(t.rx)}</h2></div><a class="textLink" href="${p(l,'medicines')}?status=rx">${esc(t.viewAll)} →</a></div><div class="rxTable">${rxRows(l,medicines,8)}</div><div class="rxNext"><div><span class="eyebrow">AFTER REFERENCE</span><strong>${l==='zh-hans'?'查到药品之后，下一步不是购买，而是确认医疗或机构流程。':l==='ja'?'医薬品を確認した後の次のステップは購入ではなく、医療または機関の経路確認です。':'After finding a medicine, the next step is not checkout — it is the right clinical or institutional pathway.'}</strong></div><a class="btn teal" href="${p(l,'inquiry')}">${l==='zh-hans'?'选择下一步':l==='ja'?'次の経路を選ぶ':'Choose the next pathway'} →</a></div></div></section></main>`;
 return shell(l,req,'TOKYO MEDI',lead,'',body);
}

export function medicinesPage(l,req){const t=UI[l],u=new URL(req.url),q=(u.searchParams.get('q')||'').trim().toLowerCase(),area=(u.searchParams.get('area')||'').trim(); let items=medicines.filter(m=>!area||m.area===area); if(q)items=items.filter(m=>[m.en,m.ja,m.zh,m.slug,m.area].join(' ').toLowerCase().includes(q));
 const intro=l==='zh-hans'?'按药名、一般名、日文名、英文名和治疗领域查询。处方药页面只做事实资料与来源导航。':l==='ja'?'医薬品名、一般名、日本語名、英語名、領域から検索します。処方薬ページは事実資料と情報源への案内に限定します。':'Search names, generic terms and therapeutic areas. Prescription pages are reference and source-navigation pages only.';
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">MEDICINE REFERENCE</div><h1>${esc(t.nav.medicines)}</h1><p>${esc(intro)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" value="${esc(u.searchParams.get('q')||'')}" placeholder="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form></div></section><section class="content"><div class="wrap"><div class="filters">${Object.entries(t.filters).map(([k,v])=>{const val=k==='all'?'':k;const qs=new URLSearchParams();if(q)qs.set('q',u.searchParams.get('q'));if(val)qs.set('area',val);return `<a class="filter ${area===val?'on':''}" href="${p(l,'medicines')}?${qs}">${esc(v)}</a>`}).join('')}</div><div class="medicineTable">${items.length?medicineRows(l,items):`<p>${l==='zh-hans'?'没有找到匹配记录。请尝试成分名、英文名或日文名。':l==='ja'?'一致する記録がありません。成分名、英語名、日本語名をお試しください。':'No matching records. Try an ingredient, English name or Japanese name.'}</p>`}</div><div class="sourceBox"><strong>${esc(t.official)}</strong><p>${l==='zh-hans'?'TOKYO MEDI 的药品索引用于帮助定位资料；药品批准状态、附件、警示等应继续回到 PMDA 和相关官方来源确认。':l==='ja'?'TOKYO MEDIの索引は資料を探すための入口です。承認状況、添付文書、安全性情報はPMDA等の一次資料で確認してください。':'TOKYO MEDI is an index for finding information. Approval status, labels and safety information should still be confirmed in PMDA and other primary sources.'}</p><a href="https://www.pmda.go.jp/english/" target="_blank" rel="noopener">PMDA ↗</a></div></div></section></main>`;
 return shell(l,req,t.nav.medicines,intro,'medicines',body);
}

export function medicineDetail(l,req,slug){const t=UI[l],m=medicines.find(x=>x.slug===slug); if(!m)return null; const desc=l==='zh-hans'?`${m.zh}（${m.en}）资料索引。处方药信息仅供参考。`:l==='ja'?`${m.ja}（${m.en}）のリファレンス。処方薬情報は資料目的です。`:`Reference index for ${m.en}. Prescription-medicine information is for reference only.`;
 const fields=l==='zh-hans'?[['中文名',m.zh],['英文一般名',m.en],['日文名',m.ja],['资料分类',labelArea(l,m.area)],['常见剂型标记',m.form],['处方属性',m.status],['最后核验',m.verified]]:l==='ja'?[['日本語名',m.ja],['一般名（英語）',m.en],['中国語名',m.zh],['領域',labelArea(l,m.area)],['剤形メモ',m.form],['区分',m.status],['最終確認',m.verified]]:[['Generic name',m.en],['Japanese name',m.ja],['Chinese name',m.zh],['Therapeutic area',labelArea(l,m.area)],['Dosage-form note',m.form],['Reference status',m.status],['Last verified',m.verified]];
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">RX REFERENCE · ${esc(t.noBuy)}</div><h1>${esc(medicineName(l,m))}</h1><p>${esc(desc)}</p></div></section><section class="content"><div class="wrap detailGrid"><div><dl class="factList">${fields.map(f=>`<div class="fact"><dt>${esc(f[0])}</dt><dd>${esc(f[1])}</dd></div>`).join('')}</dl><div class="sourceBox"><strong>${esc(t.official)}</strong><p>${l==='zh-hans'?'本站不在此页给出个体用药剂量、适应证判断或治疗推荐。请使用药品名称进入 PMDA 或相关厂家的一手资料继续确认。':l==='ja'?'本ページでは個人向けの用量、適応判断、治療推奨を提示しません。医薬品名を使ってPMDAやメーカーの一次資料をご確認ください。':'This page does not provide individualized dosing, indication decisions or treatment recommendations. Use the medicine name to continue in PMDA or manufacturer primary sources.'}</p><a href="${m.source}" target="_blank" rel="noopener">PMDA ↗</a></div></div><aside class="sideNote"><strong>${m.status} · ${esc(t.noBuy)}</strong><p>${esc(t.rxNotice)}</p><a class="btn teal" href="${p(l,'inquiry')}?medicine=${encodeURIComponent(m.en)}&type=personal">${esc(t.startPersonal)}</a></aside></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'MedicalWebPage',name:medicineName(l,m),description:desc,dateModified:m.verified,url:SITE+p(l,'medicines/'+m.slug)});
 return shell(l,req,medicineName(l,m),desc,'medicines',body,ld);
}
