import {SITE,UI,strengths,medicines,guides,hospitals} from './data.js';
import {esc,p,labelArea,shell,medicineName,medicineRows,rxRows,guideTitle,guideExcerpt,jsonLd,breadcrumbLd,htmlLang} from './core.js';

export function home(l,req){const t=UI[l]; const lead=t.heroLead; const why=[
 ['01',l==='zh-hans'?'官方来源优先':l==='ja'?'一次資料を優先':'Primary sources first',l==='zh-hans'?'重要事实尽量回到日本官方、厂家和医疗机构公开资料。':l==='ja'?'重要な事実は日本の公的機関、メーカー、医療機関の公開情報に戻ります。':'Important facts lead back to Japanese authorities, manufacturers and medical institutions.'],
 ['02',l==='zh-hans'?'医疗与商业分离':l==='ja'?'医療と商取引を分離':'Medical and commercial paths separated',l==='zh-hans'?'处方药不套普通商品购买逻辑。':l==='ja'?'処方薬を一般商品の購入導線に載せません。':'Prescription medicine does not use an ordinary shopping flow.'],
 ['03',l==='zh-hans'?'面向国际用户重组':l==='ja'?'海外利用者向けに再構成':'Built for international readers',l==='zh-hans'?'补充不同语言名称、制度背景和国际患者受理条件。':l==='ja'?'多言語名、制度背景、海外患者の受入条件を補足します。':'Add multilingual names, system context and overseas-patient intake requirements.'],
 ['04',l==='zh-hans'?'显示核验状态':l==='ja'?'確認状況を表示':'Verification status shown',l==='zh-hans'?'来源和核验日期直接显示，不把旧资料伪装成最新信息。':l==='ja'?'出典と確認日を示し、古い情報を最新として扱いません。':'Sources and verification dates are visible rather than presenting stale material as current.']
 ];
 const trustProof=l==='zh-hans'?[
  ['PMDA','药品官方资料','日本商品名、厂家、规格与 PMDA 产品级资料逐条对应。'],
  ['HOSPITAL','医院官方信息','预约、转诊、协调机构与语言要求以医院官方页面为准。'],
  ['DATES','更新时间与核验日期','官方文书更新时间与 TOKYO MEDI 核验日期分别显示。'],
  ['BOUNDARY','医疗信息边界','不远程开处方，不把处方药按普通商品售卖。']
 ]:l==='ja'?[
  ['PMDA','医薬品の公式資料','日本販売名、製造販売元、規格を PMDA の製品別資料と照合。'],
  ['HOSPITAL','病院の公式情報','予約、紹介、コーディネーター、言語要件は病院公式情報で確認。'],
  ['DATES','更新日と確認日','公式文書の更新日と TOKYO MEDI の確認日を別々に表示。'],
  ['BOUNDARY','医療情報の範囲','遠隔で処方せず、処方薬を一般商品として販売しません。']
 ]:[
  ['PMDA','Official medicine sources','Japanese product names, manufacturers and strengths are matched to PMDA product-level records.'],
  ['HOSPITAL','Official hospital information','Appointments, referrals, coordinators and language requirements are checked against hospital sources.'],
  ['DATES','Document and verification dates','Official document dates and TOKYO MEDI verification dates are shown separately.'],
  ['BOUNDARY','Scope of medical information','No remote prescribing and no ordinary ecommerce flow for prescription medicines.']
 ];
 const japanEvidence=l==='zh-hans'?[
  ['2012','山中伸弥 · iPS 细胞','成熟细胞可被重新编程为多能状态，获得诺贝尔生理学或医学奖。','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','本庶佑 · 癌症免疫治疗','因通过抑制负性免疫调节实现癌症治疗的新原理，与 James P. Allison 共同获奖。','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','大村智 · 抗寄生虫治疗','其研究促成针对线虫寄生感染的新疗法，与 William C. Campbell 共同获奖。','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ]:l==='ja'?[
  ['2012','山中伸弥 · iPS細胞','成熟細胞を多能性状態へ再プログラムできる発見でノーベル生理学・医学賞。','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','本庶佑 · がん免疫療法','負の免疫制御の阻害によるがん治療の発見で James P. Allison と共同受賞。','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','大村智 · 抗寄生虫治療','線虫寄生感染に対する新規治療の発見で William C. Campbell と共同受賞。','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ]:[
  ['2012','Shinya Yamanaka · iPS cells','Awarded for the discovery that mature cells can be reprogrammed to become pluripotent.','https://www.nobelprize.org/prizes/medicine/2012/summary/'],
  ['2018','Tasuku Honjo · cancer immunotherapy','Awarded jointly with James P. Allison for cancer therapy by inhibition of negative immune regulation.','https://www.nobelprize.org/prizes/medicine/2018/summary/'],
  ['2015','Satoshi Ōmura · antiparasitic therapy','Awarded jointly with William C. Campbell for discoveries concerning a novel therapy against roundworm infections.','https://www.nobelprize.org/prizes/medicine/2015/omura/facts/']
 ];
 const patientSteps=l==='zh-hans'?[
  ['01','准备资料','整理诊断、检查、影像、当前用药和转诊资料。'],
  ['02','医院受理 / 预约','确认医院是否要求转诊、协调机构或国际患者部门。'],
  ['03','挂号 / 受付','按医院要求完成初诊登记与身份、资料确认。'],
  ['04','医生诊察','医生了解病情并决定是否需要进一步检查。'],
  ['05','检查 / 判断','检查和治疗方案由医生根据实际情况决定。'],
  ['06','处方','只有医生判断有需要时才会开具处方。'],
  ['07','药局取药','按医院流程到院内或院外药局调剂处方药。']
 ]:l==='ja'?[
  ['01','資料準備','診断、検査、画像、服薬情報、紹介資料を整理。'],
  ['02','受入 / 予約','紹介状、コーディネーター、国際患者窓口の要否を確認。'],
  ['03','受付','病院の手順に従って初診受付と資料確認。'],
  ['04','医師の診察','医師が状態を確認し、追加検査の要否を判断。'],
  ['05','検査 / 判断','検査と治療方針は医師が実際の状態に基づき判断。'],
  ['06','処方','必要と判断された場合に医師が処方。'],
  ['07','薬局','院内または院外薬局で処方箋に基づき調剤。']
 ]:[
  ['01','Prepare records','Organize diagnosis, tests, imaging, current medicines and referral material.'],
  ['02','Hospital intake / appointment','Confirm referral, coordinator and international-patient requirements.'],
  ['03','Registration','Complete first-visit registration and document checks.'],
  ['04','Clinician consultation','A clinician assesses the condition and decides whether more tests are needed.'],
  ['05','Tests / clinical decision','Testing and treatment plans depend on the clinical assessment.'],
  ['06','Prescription','A prescription is issued only when the clinician decides it is appropriate.'],
  ['07','Pharmacy','The prescription is dispensed by an in-hospital or community pharmacy.']
 ];
 const institutionSteps=l==='zh-hans'?[
  ['01','确认品项','核对日本商品名、一般名和厂家。'],
  ['02','确认规格','确认剂型、含量、数量与目的地。'],
  ['03','提交资质','说明医疗机构、药局或企业资质。'],
  ['04','机构询价','按合规流程确认可供应性与后续条件。']
 ]:l==='ja'?[
  ['01','品目確認','日本販売名、一般名、メーカーを確認。'],
  ['02','規格確認','剤形、含量、数量、仕向地を確認。'],
  ['03','資格情報','医療機関、薬局、企業の資格情報を提示。'],
  ['04','機関照会','適切な手続きで供給可否と条件を確認。']
 ]:[
  ['01','Identify item','Confirm Japanese product name, generic and manufacturer.'],
  ['02','Confirm specification','Confirm dosage form, strength, quantity and destination.'],
  ['03','Provide credentials','Provide institution, pharmacy or company credentials.'],
  ['04','Institutional inquiry','Confirm availability and conditions through the appropriate process.']
 ];
 const travelSteps=l==='zh-hans'?[['01','准备病历','整理诊断、近期报告、影像和用药清单。'],['02','确认受理方式','先看医院是否要求协调机构、转诊或国际患者部门。'],['03','准备翻译','只翻译接诊机构真正需要的材料。'],['04','确认费用与随访','在出发前确认收费方式、付款要求和回国后资料衔接。']]:l==='ja'?[['01','診療情報を準備','診断、最近の報告、画像、服薬情報を整理。'],['02','受入経路を確認','コーディネーター、紹介元、国際患者部門の要否を確認。'],['03','翻訳を準備','受入先が必要とする資料を優先して翻訳。'],['04','費用とフォロー','費用、支払条件、帰国後の連携を確認。']]:[['01','Prepare records','Organize diagnosis, recent reports, imaging and medication list.'],['02','Confirm intake route','Check whether a coordinator, referral or international office is required.'],['03','Prepare translation','Translate what the receiving institution actually needs.'],['04','Confirm cost & follow-up','Clarify billing, payment and post-return continuity before travel.']];
 const body=`<main><section class="hero"><div class="wrap heroGrid"><div><div class="kicker">${esc(t.heroKicker)}</div><h1>${esc(t.heroTitle)}</h1><p class="lead">${esc(lead)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}" aria-label="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="heroMeta"><span><i></i>${l==='zh-hans'?'官方来源优先':l==='ja'?'一次資料を優先':'Primary sources first'}</span><span><i></i>${l==='zh-hans'?'三语信息结构':l==='ja'?'3言語構造':'Three-language structure'}</span><span><i></i>${l==='zh-hans'?'处方药无直接购买':l==='ja'?'処方薬の直接販売なし':'No direct Rx sales'}</span></div></div><div class="heroStage"><figure class="heroPhoto"><img src="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600" srcset="https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=78&w=800 800w, https://images.unsplash.com/photo-1766297246931-7b861269dab0?auto=format&fit=crop&q=82&w=1600 1600w" sizes="(max-width:1080px) 100vw, 44vw" width="1600" height="1100" fetchpriority="high" decoding="async" alt="${l==='zh-hans'?'现代医学研究实验室':l==='ja'?'先端医療研究ラボ':'Modern medical research laboratory'}"><div class="heroPhotoVeil"></div><figcaption><span>JAPAN · RESEARCH · MEDICINE</span><strong>${l==='zh-hans'?'从原始资料到下一步医疗路径':l==='ja'?'一次資料から次の医療経路へ':'From primary sources to the next care pathway'}</strong></figcaption></figure><div class="route"><div class="routeTitle">${esc(t.routeTitle)}</div>${t.routeItems.map((x,i)=>`<a class="routeRow" href="${p(l,x[0])}"><span class="routeNo">0${i+1}</span><div><strong>${esc(x[1])}</strong><small>${esc(x[2])}</small></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="sourceRail" aria-label="Primary medical sources"><div class="wrap sourceRailInner"><span class="sourceRailLead">${l==='zh-hans'?'资料核验优先回到日本一手来源':l==='ja'?'検証は日本の一次情報を優先':'Verification starts with Japanese primary sources'}</span><div class="sourceRailMarks"><span><b>PMDA</b><small>Regulation / Safety</small></span><span><b>MHLW</b><small>Policy / Health system</small></span><span><b>RAD-AR</b><small>Patient medicine information</small></span></div></div></section>
 <section class="section proofSection" id="trust"><div class="wrap"><div class="sectionHead compactHead"><div><div class="eyebrow">01 · SOURCES & VERIFICATION</div><h2>${l==='zh-hans'?'资料来源与核验':l==='ja'?'情報源と確認':'Sources and verification'}</h2></div><p>${l==='zh-hans'?'药品与赴日医疗信息均标明来源、核验日期和适用范围。':l==='ja'?'医薬品と医療渡航情報について、情報源、確認日、適用範囲を明示します。':'Medicine and medical-travel information is presented with sources, verification dates and scope.'}</p></div><div class="proofGrid">${trustProof.map(x=>`<div class="proofItem"><span>${esc(x[0])}</span><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div>`).join('')}</div></div></section>
 <section class="section strength evidenceSection" id="strength"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">02 · MEDICAL RESEARCH IN JAPAN</div><h2>${esc(t.strength)}</h2></div><p>${esc(t.strengthLead)}</p></div><div class="evidenceList">${japanEvidence.map(x=>`<a class="evidenceRow" href="${x[3]}" target="_blank" rel="noopener"><span class="evidenceYear">${esc(x[0])}</span><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div><b>NOBEL PRIZE ↗</b></a>`).join('')}</div></div></section>
 <section class="section database" id="database"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">03 · MEDICINE DATABASE</div><h2>${esc(t.medicineDb)}</h2></div><p>${esc(t.medicineLead)}</p></div><div class="dbPanel"><div class="dbSearch"><h3>${esc(t.search)}</h3><p>${esc(t.noBuy)}</p><div class="dbProof"><span><b>${medicines.length}</b>${l==='zh-hans'?'条产品级核验记录':l==='ja'?'件の製品別確認記録':'product-level verified records'}</span><span><b>PMDA</b>${l==='zh-hans'?'产品级一手来源':l==='ja'?'製品別一次資料':'product-level primary sources'}</span></div><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" placeholder="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form><div class="chips">${Object.entries(t.filters).map(([k,v])=>`<a class="chip" href="${p(l,'medicines')}?area=${k==='all'?'':k}">${esc(v)}</a>`).join('')}</div></div><div class="medicineRows">${medicineRows(l,medicines,7)}</div></div></div></section>
 <section class="section pathwaySection" id="pathway"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">04 · CARE & INQUIRY</div><h2>${l==='zh-hans'?'就医流程与机构咨询':l==='ja'?'受診の流れと機関向け照会':'Care pathway and institutional inquiry'}</h2></div><p>${l==='zh-hans'?'个人患者按医院要求进入预约、初诊和处方流程；医疗机构、药局和企业使用独立的品项咨询流程。':l==='ja'?'個人患者は病院の手順に沿って予約・初診・処方へ進み、医療機関・薬局・企業は別の品目照会手続きを利用します。':'Individuals follow hospital intake, consultation and prescribing pathways; institutions, pharmacies and companies use a separate product-inquiry process.'}</p></div><div class="pathwaySplit"><div class="patientPath"><div class="pathTitle"><span>A</span><div><small>PATIENT / INDIVIDUAL</small><h3>${l==='zh-hans'?'正规就医与处方流程':l==='ja'?'受診から処方まで':'Care and prescription pathway'}</h3></div></div><div class="clinicalFlow">${patientSteps.map(x=>`<div class="clinicalStep"><span>${esc(x[0])}</span><div><strong>${esc(x[1])}</strong><p>${esc(x[2])}</p></div></div>`).join('')}</div><a class="textLink" href="${p(l,'travel')}">${l==='zh-hans'?'查看医院受理规则':l==='ja'?'病院の受入条件を見る':'See hospital intake rules'} →</a></div><div class="institutionPath"><div class="pathTitle"><span>B</span><div><small>INSTITUTION / PHARMACY / COMPANY</small><h3>${l==='zh-hans'?'机构药品询价流程':l==='ja'?'機関向け医薬品照会':'Institutional medicine inquiry'}</h3></div></div><div class="institutionFlow">${institutionSteps.map(x=>`<div class="institutionStep"><span>${esc(x[0])}</span><div><strong>${esc(x[1])}</strong><p>${esc(x[2])}</p></div></div>`).join('')}</div><a class="textLink" href="${p(l,'inquiry')}?type=institution">${esc(t.startInstitution)} →</a></div></div><div class="clinicalNotice">${l==='zh-hans'?'部分大型医院在初诊登记前可能要求转诊信、医疗协调机构或国际患者部门预审，请以各医院最新规定为准。':l==='ja'?'大規模病院では初診受付の前に、紹介状、医療コーディネーター、国際患者部門の事前確認が必要な場合があります。最新の病院案内をご確認ください。':'Some major hospitals may require referral documents, a medical coordinator or international-patient review before first-visit registration. Check the hospital’s latest requirements.'}</div></div></section>
 <section class="section" id="travel"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">05 · MEDICAL TRAVEL</div><h2>${esc(t.travel)}</h2></div><a class="textLink" href="${p(l,'travel')}">${esc(t.viewAll)} →</a></div><div class="travelGrid"><div class="travelVisual"><img src="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600" srcset="https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=76&w=800 800w, https://images.unsplash.com/photo-1742647230897-230050b9f0aa?auto=format&fit=crop&q=80&w=1600 1600w" sizes="(max-width:1080px) 100vw, 42vw" width="1600" height="1050" loading="lazy" decoding="async" alt="Tokyo"><div class="travelVisualCopy"><span>TOKYO / JAPAN</span><strong>${l==='zh-hans'?'不是先选医院，而是先确认医疗需求与受理路径。':l==='ja'?'病院選びの前に、医療ニーズと受入経路を確認します。':'Start with the medical need and intake route — not a random hospital list.'}</strong></div></div><div class="travelFlow"><div class="timeline">${travelSteps.map(s=>`<div class="step"><strong>${esc(s[0])} · ${esc(s[1])}</strong><p>${esc(s[2])}</p></div>`).join('')}</div><div class="hospitalPreview">${hospitals.slice(0,5).map(h=>`<a class="hospitalRow" href="${p(l,'travel')}#${h.slug}"><div><strong>${esc(h.name)}</strong><small>${esc(h.ja)} · ${esc(h.path)}</small></div><span>${esc(h.city)}</span><b>→</b></a>`).join('')}</div></div></div></div></section>
 <section class="section trustSection"><div class="wrap trustLayout"><div class="trustStatement"><div class="eyebrow">06 · METHOD</div><h2>${esc(t.why)}</h2><p>${l==='zh-hans'?'TOKYO MEDI 的价值不是“内容更多”，而是把来源、医疗边界、国际用户语境和下一步行动放在同一个信息结构里。':l==='ja'?'TOKYO MEDIの価値は情報量ではなく、出典、医療上の境界、海外利用者の文脈、次の行動を一つの構造にまとめることです。':'TOKYO MEDI is not about having more content. It connects sources, medical boundaries, international context and the next action in one information structure.'}</p><a class="textLink" href="${p(l,'sources')}">${esc(t.official)} →</a></div><div class="whyStack">${why.map(x=>`<div class="whyItem"><span>${x[0]}</span><div><h3>${esc(x[1])}</h3><p>${esc(x[2])}</p></div></div>`).join('')}</div></div></section>
 <section class="section guides" id="guides"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">07 · GUIDES</div><h2>${esc(t.guides)}</h2></div><a class="textLink" href="${p(l,'guides')}">${esc(t.viewAll)} →</a></div><div class="guideLayout"><a class="featuredGuide" href="${p(l,'guides/'+guides[0].slug)}"><div><div class="eyebrow">FEATURED · ${guides[0].date}</div><h3>${esc(guideTitle(l,guides[0]))}</h3><p>${esc(guideExcerpt(l,guides[0]))}</p></div><span class="textLink">${esc(t.read)} →</span></a><div class="guideList">${guides.slice(1).map(g=>`<a class="guideRow" href="${p(l,'guides/'+g.slug)}"><div><h3>${esc(guideTitle(l,g))}</h3><p>${esc(guideExcerpt(l,g))}</p></div><b>→</b></a>`).join('')}</div></div></div></section>
 <section class="section rxShowcase" id="prescription"><div class="wrap"><div class="sectionHead"><div><div class="eyebrow">08 · PRESCRIPTION REFERENCE</div><h2>${esc(t.rx)}</h2></div><a class="textLink" href="${p(l,'medicines')}?status=rx">${esc(t.viewAll)} →</a></div><div class="rxTable">${rxRows(l,medicines,8)}</div><div class="rxNext"><div><span class="eyebrow">AFTER REFERENCE</span><strong>${l==='zh-hans'?'查到药品之后，下一步不是购买，而是确认医疗或机构流程。':l==='ja'?'医薬品を確認した後の次のステップは購入ではなく、医療または機関の経路確認です。':'After finding a medicine, the next step is not checkout — it is the right clinical or institutional pathway.'}</strong></div><a class="btn teal" href="#pathway">${l==='zh-hans'?'查看两条路径':l==='ja'?'2つの経路を見る':'See both pathways'} →</a></div></div></section> <section class="section inquirySection" id="inquiry"><div class="wrap"><div class="sectionHead inquiryHead"><div><div class="eyebrow">09 · NEXT STEP</div><h2>${esc(t.inquiry)}</h2></div><p>${l==='zh-hans'?'先判断你是谁，再决定信息需要走向医疗咨询还是机构询价。两条路径从这里开始分开。':l==='ja'?'まず利用者の立場を確認し、医療相談と機関照会の経路をここで分けます。':'Identify who you are first. Patient guidance and institutional sourcing split into two different paths here.'}</p></div><div class="decisionRail"><span>01 ${l==='zh-hans'?'查资料':l==='ja'?'資料確認':'REFERENCE'}</span><i></i><span>02 ${l==='zh-hans'?'判断路径':l==='ja'?'経路判断':'ROUTE'}</span><i></i><span>03 ${l==='zh-hans'?'咨询/询价':l==='ja'?'相談・照会':'ACTION'}</span></div><div class="inquirySplit"><div class="inquiryCard"><div class="eyebrow">A · PATIENT / INDIVIDUAL</div><h3>${esc(t.personal)}</h3><p>${esc(t.personalDesc)}</p><ul><li>${l==='zh-hans'?'确认医院受理、转诊或协调机构要求':l==='ja'?'病院の受入・紹介・コーディネーター要件を確認':'Confirm hospital intake, referral or coordinator requirements'}</li><li>${l==='zh-hans'?'完成预约与挂号/受付':l==='ja'?'予約と受付を行う':'Complete appointment and registration'}</li><li>${l==='zh-hans'?'由医生决定检查、治疗与是否开处方':l==='ja'?'検査・治療・処方の要否は医師が判断':'A clinician decides testing, treatment and whether to prescribe'}</li></ul><a class="btn teal" href="${p(l,'travel')}">${esc(t.startPersonal)}</a></div><div class="inquiryCard"><div class="eyebrow">B · INSTITUTIONAL</div><h3>${esc(t.institution)}</h3><p>${esc(t.institutionDesc)}</p><ul><li>${l==='zh-hans'?'机构名称与国家/地区':l==='ja'?'機関名と国・地域':'Institution and country/region'}</li><li>${l==='zh-hans'?'药品、规格、数量与目的地':l==='ja'?'医薬品、規格、数量、仕向地':'Medicine, specification, quantity and destination'}</li><li>${l==='zh-hans'?'许可证或资质信息':l==='ja'?'許可・資格情報':'Licence or credential information'}</li></ul><a class="btn" href="${p(l,'inquiry')}?type=institution">${esc(t.startInstitution)}</a></div></div><div class="rxNote">${esc(t.rxNotice)}</div></div></section>
</main>`;
 const homeTitle=l==='zh-hans'?'日本医药品资料库与赴日医疗':l==='ja'?'日本医薬品リファレンスと医療渡航':'Japanese Medicine Reference & Medical Travel';
 return shell(l,req,homeTitle,lead,'',body);
}

export function medicinesPage(l,req){const t=UI[l],u=new URL(req.url),q=(u.searchParams.get('q')||'').trim().toLowerCase(),area=(u.searchParams.get('area')||'').trim(); let items=medicines.filter(m=>!area||m.area===area); if(q)items=items.filter(m=>[m.en,m.ja,m.zh,m.slug,m.area,m.productJa,m.brandEn,m.manufacturerJa,m.strengths,...(m.alternateProductsJa||[])].filter(Boolean).join(' ').toLowerCase().includes(q));
 const intro=l==='zh-hans'?'按药名、一般名、日文名、英文名和治疗领域查询。处方药页面只做事实资料与来源导航。':l==='ja'?'医薬品名、一般名、日本語名、英語名、領域から検索します。処方薬ページは事実資料と情報源への案内に限定します。':'Search names, generic terms and therapeutic areas. Prescription pages are reference and source-navigation pages only.';
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">MEDICINE REFERENCE</div><h1>${esc(t.nav.medicines)}</h1><p>${esc(intro)}</p><form class="searchBox" action="${p(l,'medicines')}" method="get"><input name="q" value="${esc(u.searchParams.get('q')||'')}" placeholder="${esc(t.searchPlaceholder)}"><button>${esc(t.search)}</button></form></div></section><section class="content"><div class="wrap"><div class="filters">${Object.entries(t.filters).map(([k,v])=>{const val=k==='all'?'':k;const qs=new URLSearchParams();if(q)qs.set('q',u.searchParams.get('q'));if(val)qs.set('area',val);return `<a class="filter ${area===val?'on':''}" href="${p(l,'medicines')}?${qs}">${esc(v)}</a>`}).join('')}</div><div class="medicineTable">${items.length?medicineRows(l,items):`<p>${l==='zh-hans'?'没有找到匹配记录。请尝试成分名、英文名或日文名。':l==='ja'?'一致する記録がありません。成分名、英語名、日本語名をお試しください。':'No matching records. Try an ingredient, English name or Japanese name.'}</p>`}</div><div class="sourceBox"><strong>${esc(t.official)}</strong><p>${l==='zh-hans'?'TOKYO MEDI 的药品索引用于帮助定位资料；药品批准状态、附件、警示等应继续回到 PMDA 和相关官方来源确认。':l==='ja'?'TOKYO MEDIの索引は資料を探すための入口です。承認状況、添付文書、安全性情報はPMDA等の一次資料で確認してください。':'TOKYO MEDI is an index for finding information. Approval status, labels and safety information should still be confirmed in PMDA and other primary sources.'}</p><a href="https://www.pmda.go.jp/english/" target="_blank" rel="noopener">PMDA ↗</a></div></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:t.nav.medicines,description:intro,url:SITE+p(l,'medicines'),inLanguage:htmlLang(l),mainEntity:{'@type':'ItemList',itemListElement:items.map((m,i)=>({'@type':'ListItem',position:i+1,name:m.productJa||m.en,url:SITE+p(l,'medicines/'+m.slug)}))}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.medicines,p(l,'medicines')]]);
 return shell(l,req,t.nav.medicines,intro,'medicines',body,ld);
}

export function medicineDetail(l,req,slug){const t=UI[l],m=medicines.find(x=>x.slug===slug); if(!m)return null;
 const scopeNote=m.scope==='representative'?(l==='zh-hans'?'此页以一个日本代表性商品为锚点；同一成分可能还有其他日本商品。':l==='ja'?'このページは日本の代表的な製品を基準にしています。同一成分には他の製品が存在する場合があります。':'This page anchors the ingredient to one representative Japanese product; other Japanese products may exist for the same ingredient.'):'';
 const statusNote=l==='zh-hans'?m.statusNoteZh:l==='ja'?m.statusNoteJa:m.statusNoteEn;
 const desc=l==='zh-hans'?`${m.productJa}｜${m.zh}（${m.en}）官方资料索引。${scopeNote}`:l==='ja'?`${m.productJa}｜${m.en} の公式資料リファレンス。${scopeNote}`:`${m.brandEn||m.productJa} / ${m.en}: verified Japanese product reference. ${scopeNote}`;
 const fields=l==='zh-hans'?[
   ['日本商品名',m.productJa],['品牌',m.brandEn],['中文名',m.zh],['英文一般名',m.en],['日文一般名',m.ja],['制造销售企业',m.manufacturerJa],['规格 / 含量',m.strengths],['剂型',m.form],['治疗领域',labelArea(l,m.area)],['监管属性',m.status],['添付文书更新',m.labelUpdated],['TOKYO MEDI 核验',m.verifiedAt]
 ]:l==='ja'?[
   ['日本販売名',m.productJa],['ブランド',m.brandEn],['一般名（日本語）',m.ja],['一般名（英語）',m.en],['中国語名',m.zh],['製造販売元',m.manufacturerJa],['規格',m.strengths],['剤形',m.form],['領域',labelArea(l,m.area)],['区分',m.status],['添付文書更新',m.labelUpdated],['TOKYO MEDI 確認日',m.verifiedAt]
 ]:[
   ['Japan product name',m.productJa],['Brand',m.brandEn],['Generic name',m.en],['Japanese generic name',m.ja],['Chinese name',m.zh],['Marketing authorization holder',m.manufacturerJa],['Strengths',m.strengths],['Dosage form',m.form],['Therapeutic area',labelArea(l,m.area)],['Regulatory status',m.status],['Label updated',m.labelUpdated],['TOKYO MEDI verified',m.verifiedAt]
 ];
 const alternates=(m.alternateProductsJa||[]).length?`<div class="sourceBox altProducts"><strong>${l==='zh-hans'?'同成分的其他日本商品':l==='ja'?'同一成分の他製品':'Other Japanese products with the same ingredient'}</strong><p>${esc(m.alternateProductsJa.join(' · '))}</p><p>${esc(scopeNote)}</p></div>`:'';
 const body=`<main><section class="pageHero medicineHero"><div class="wrap"><div class="eyebrow">${esc(m.status)} · ${esc(t.noBuy)}</div><h1>${esc(medicineName(l,m))}</h1><p>${esc(desc)}</p><div class="verificationStrip"><span><b>PMDA</b>${l==='zh-hans'?'产品级来源':l==='ja'?'製品別一次資料':'product-level source'}</span><span><b>${esc(m.labelUpdated)}</b>${l==='zh-hans'?'添付文书更新':l==='ja'?'添付文書更新':'label updated'}</span><span><b>${esc(m.verifiedAt)}</b>${l==='zh-hans'?'本站核验':l==='ja'?'当サイト確認':'site verified'}</span></div></div></section><section class="content"><div class="wrap detailGrid"><div><dl class="factList">${fields.map(f=>`<div class="fact"><dt>${esc(f[0])}</dt><dd>${esc(f[1]||'—')}</dd></div>`).join('')}</dl>${statusNote?`<div class="statusNote"><strong>${l==='zh-hans'?'监管状态说明':l==='ja'?'区分に関する注記':'Regulatory status note'}</strong><p>${esc(statusNote)}</p></div>`:''}${alternates}<div class="sourceBox sourceActions"><strong>${esc(t.official)}</strong><p>${l==='zh-hans'?'以下链接直接进入该日本品项的 PMDA 官方资料。患者向页面与医疗专业人员页面分开提供。':l==='ja'?'以下はこの製品のPMDA公式資料です。一般向け情報と医療関係者向け情報を分けて案内します。':'These links go directly to PMDA records for this Japanese product. Professional and patient-facing sources are separated.'}</p><div class="sourceButtons"><a class="btn teal" href="${m.source}" target="_blank" rel="noopener">PMDA · ${l==='zh-hans'?'专业资料':l==='ja'?'医療関係者向け':'professional'} ↗</a>${m.patientSource?`<a class="btn ghost" href="${m.patientSource}" target="_blank" rel="noopener">PMDA · ${l==='zh-hans'?'患者资料':l==='ja'?'一般向け':'patient'} ↗</a>`:''}</div></div></div><aside class="sideNote"><strong>${esc(m.status)} · ${esc(t.noBuy)}</strong><p>${esc(t.rxNotice)}</p><div class="sideVerify"><span>${l==='zh-hans'?'来源':'Source'}<b>PMDA</b></span><span>${l==='zh-hans'?'核验':'Verified'}<b>${esc(m.verifiedAt)}</b></span></div><a class="btn teal" href="${p(l,'inquiry')}?medicine=${encodeURIComponent(m.productJa)}&type=personal">${esc(t.startPersonal)}</a></aside></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'MedicalWebPage',name:medicineName(l,m),description:desc,dateModified:m.verifiedAt,url:SITE+p(l,'medicines/'+m.slug),inLanguage:htmlLang(l),publisher:{'@id':SITE+'/#organization'},isPartOf:{'@id':SITE+'/#website'},about:{'@type':'Drug',name:m.en,alternateName:[m.productJa,m.brandEn,m.ja,m.zh].filter(Boolean),nonProprietaryName:m.en,proprietaryName:m.brandEn||undefined,activeIngredient:m.en,dosageForm:m.form,manufacturer:{'@type':'Organization',name:m.manufacturerJa},sameAs:m.source,...(m.status==='Rx'?{prescriptionStatus:'https://schema.org/PrescriptionOnly'}:{})}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.medicines,p(l,'medicines')],[medicineName(l,m),p(l,'medicines/'+m.slug)]]);
 return shell(l,req,medicineName(l,m),desc,'medicines',body,ld);
}
