import {SITE,EMAIL,UI,strengths,guides,hospitals,sourceLinks} from './data.js';
import {esc,p,shell,guideTitle,guideExcerpt,jsonLd,breadcrumbLd,htmlLang} from './core.js';

export function guidesPage(l,req){const t=UI[l],intro=l==='zh-hans'?'指南内容标明资料来源与日期，并区分一般信息与需要专业医疗判断的内容。':l==='ja'?'ガイドでは情報源と日付を明示し、一般情報と専門的な医療判断が必要な内容を区別します。':'Guides identify sources and dates and distinguish general information from matters requiring professional clinical judgment.';
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">EDITORIAL & GUIDES</div><h1>${esc(t.nav.guides)}</h1><p>${esc(intro)}</p></div></section><section class="content"><div class="wrap guideList">${guides.map(g=>`<a class="guideRow" href="${p(l,'guides/'+g.slug)}"><div><div class="eyebrow">${g.date}</div><h3>${esc(guideTitle(l,g))}</h3><p>${esc(guideExcerpt(l,g))}</p></div><b>→</b></a>`).join('')}</div></section></main>`; const ld=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:t.nav.guides,description:intro,url:SITE+p(l,'guides'),inLanguage:htmlLang(l),mainEntity:{'@type':'ItemList',itemListElement:guides.map((g,i)=>({'@type':'ListItem',position:i+1,name:guideTitle(l,g),url:SITE+p(l,'guides/'+g.slug)}))}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.guides,p(l,'guides')]]); return shell(l,req,t.nav.guides,intro,'guides',body,ld);}
export function guideDetail(l,req,slug){const g=guides.find(x=>x.slug===slug); if(!g)return null; const t=UI[l],title=guideTitle(l,g),desc=guideExcerpt(l,g); const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">GUIDE · ${g.date}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div></section><section class="content"><div class="wrap article"><div class="articleMeta"><span>${esc(t.updated)}: ${g.date}</span><span>${esc(t.noBuy)}</span></div>${(g.sections[l]||g.sections.en).map(s=>`<h2>${esc(s[0])}</h2><p>${esc(s[1])}</p>`).join('')}<div class="articleFooter"><div class="sourceBox"><strong>${esc(t.official)}</strong><p>PMDA · MHLW · ${l==='zh-hans'?'日本医疗机构官方页面':l==='ja'?'日本の医療機関公式ページ':'Japanese medical-institution official pages'}</p><a href="${p(l,'sources')}">${esc(t.nav.sources)} →</a></div></div></div></section></main>`; const ld=jsonLd({'@context':'https://schema.org','@type':'Article',headline:title,description:desc,datePublished:g.date,dateModified:g.date,mainEntityOfPage:SITE+p(l,'guides/'+g.slug),url:SITE+p(l,'guides/'+g.slug),inLanguage:htmlLang(l),author:{'@id':SITE+'/#organization'},publisher:{'@id':SITE+'/#organization'}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.guides,p(l,'guides')],[title,p(l,'guides/'+g.slug)]]); return shell(l,req,title,desc,'guides',body,ld);}

export function travelPage(l,req){const t=UI[l],intro=l==='zh-hans'?'按医疗需求、病历准备、医院受理条件和预约要求整理赴日就医信息。下列机构作为官方入口索引，具体条件以医院最新页面为准。':l==='ja'?'医療ニーズ、診療情報、病院の受入条件、予約要件を整理しています。以下の医療機関は公式窓口への索引として掲載し、具体的な条件は各病院の最新情報をご確認ください。':'Care-in-Japan information is organized around medical needs, records, hospital intake and appointment requirements. The institutions below are official-entry references; confirm current conditions on each hospital’s latest page.'; const u=new URL(req.url),area=u.searchParams.get('area')||'',items=hospitals.filter(h=>!area||h.area===area);
 const opts=l==='zh-hans'?[['','全部'],['oncology','肿瘤'],['cardio','心脑血管'],['checkup','体检'],['multidisciplinary','综合/大学医院']]:l==='ja'?[['','すべて'],['oncology','腫瘍'],['cardio','循環器・脳血管'],['checkup','健診'],['multidisciplinary','大学病院・総合']]:[['','All'],['oncology','Oncology'],['cardio','Cardio / cerebrovascular'],['checkup','Checkup'],['multidisciplinary','University / multidisciplinary']];
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">MEDICAL TRAVEL</div><h1>${esc(t.nav.travel)}</h1><p>${esc(intro)}</p></div></section><section class="content"><div class="wrap"><div class="filters">${opts.map(([v,n])=>`<a class="filter ${area===v?'on':''}" href="${p(l,'travel')}${v?'?area='+v:''}">${esc(n)}</a>`).join('')}</div><div class="hospitalGrid">${items.map(h=>`<article class="hospitalCard" id="${h.slug}"><div class="eyebrow">${esc(h.city)} · ${esc(h.area.toUpperCase())}</div><h2>${esc(h.name)}</h2><p class="hospitalJa">${esc(h.ja)}</p><div class="hospitalRoute">${esc(h.path)}</div><ul class="hospitalFacts">${(h.facts?.[l]||h.facts?.en||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="hospitalMeta"><span>${esc(t.updated)} ${h.verified}</span>${h.officialUpdated?`<span>Official page ${esc(h.officialUpdated)}</span>`:''}</div><a href="${h.url}" target="_blank" rel="noopener">${esc(t.hospitalOfficial)} ↗</a></article>`).join('')}</div><div class="rxNote">${l==='zh-hans'?'医院受理方式、翻译、协调机构要求、费用和可预约科室可能随时间变化。安排行程前请以医院最新官方信息确认。':l==='ja'?'受入方法、通訳、コーディネーター、費用、予約可能な診療科は変更される場合があります。渡航前に病院の最新公式情報をご確認ください。':'Hospital intake, interpretation, coordinator requirements, fees and available departments can change. Confirm the hospital’s latest official information before arranging travel.'}</div></div></section></main>`; const ld=jsonLd({'@context':'https://schema.org','@type':'CollectionPage',name:t.nav.travel,description:intro,url:SITE+p(l,'travel'),inLanguage:htmlLang(l),mainEntity:{'@type':'ItemList',itemListElement:items.map((h,i)=>({'@type':'ListItem',position:i+1,name:h.name,url:h.url}))}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.travel,p(l,'travel')]]); return shell(l,req,t.nav.travel,intro,'travel',body,ld);}

export function sourcesPage(l,req){const t=UI[l],intro=l==='zh-hans'?'本站发布药品和医疗信息时，优先采用日本监管机构、制造销售企业和医疗机构的官方资料，并标注核验日期。':l==='ja'?'医薬品・医療情報の掲載では、日本の規制当局、製造販売元、医療機関の公式資料を優先し、確認日を表示します。':'Published medicine and healthcare information prioritizes official Japanese regulatory, manufacturer and medical-institution sources and shows verification dates.';
 const levels=l==='zh-hans'?[['监管机构','批准状态、警示、制度与安全信息首先看 PMDA / 厚生劳动省。'],['医疗机构与厂家','接诊条件、产品资料和更新信息以发布主体的官方页面为准。'],['论文与学术资料','用于解释研究背景与证据，不替代批准状态或临床判断。'],['专业媒体与二手来源','用于发现线索，重要事实再回到更高等级来源核验。']]:l==='ja'?[['規制当局','承認、安全性、制度はPMDA・厚生労働省を優先。'],['医療機関・メーカー','受入条件、製品資料、更新情報は発信主体の公式ページで確認。'],['論文・学術資料','研究背景とエビデンスの理解に使い、承認状況や臨床判断の代わりにはしない。'],['専門メディア・二次情報','情報発見に使い、重要事項は上位の一次資料で再確認。']]:[['Regulators','Use PMDA / MHLW first for approvals, safety, regulation and official status.'],['Institutions & manufacturers','Use the publishing institution for intake rules, product information and current updates.'],['Academic literature','Use papers for research context and evidence, not as a substitute for approval status or clinical judgment.'],['Professional media & secondary sources','Use them to discover leads, then verify material facts in higher-level sources.']];
 const policies=l==='zh-hans'?[
  ['产品核验','只有日本商品名、一般名、制造销售企业、规格和产品级官方来源能够互相对应时，才标记为“已核验”。'],
  ['日期分开','“添付文书更新”来自官方文书日期；“TOKYO MEDI 核验”表示本站最后一次人工/编辑核对日期，两者绝不混用。'],
  ['医疗边界','本站不把资料整理包装成个体处方、剂量、适应证判断或治疗推荐；需要临床判断的内容交给医生和药师。'],
  ['更正机制','发现名称、厂家、规格、链接或日期错误，请附页面地址与官方来源发送至 '+EMAIL+'。更正后重新标记核验日期。']
 ]:l==='ja'?[
  ['製品確認','日本販売名、一般名、製造販売元、規格、製品別一次資料が相互に一致した場合のみ「確認済み」とします。'],
  ['日付を分離','「添付文書更新」は公式文書の日付、「TOKYO MEDI確認日」は当サイトが最後に照合した日付です。混同しません。'],
  ['医療上の境界','個別の処方、用量、適応判断、治療推奨は行いません。臨床判断は医師・薬剤師等の専門家に委ねます。'],
  ['訂正方針','名称、メーカー、規格、リンク、日付の誤りはページURLと一次資料を添えて '+EMAIL+' までお知らせください。']
 ]:[
  ['Product verification','A record is marked verified only when the Japanese product name, generic name, marketing authorization holder, strengths and product-level primary source match.'],
  ['Dates stay separate','“Label updated” is the official document date. “TOKYO MEDI verified” is the last editorial verification date. They are never presented as the same thing.'],
  ['Medical boundary','We do not convert reference material into individualized prescriptions, dosing, indication decisions or treatment recommendations.'],
  ['Corrections','If a name, manufacturer, strength, link or date is wrong, send the page URL and primary source to '+EMAIL+'. A correction triggers a new verification date.']
 ];
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">SOURCE & EDITORIAL POLICY</div><h1>${esc(t.nav.sources)}</h1><p>${esc(intro)}</p></div></section><section class="content"><div class="wrap"><div class="sourceHierarchy">${levels.map(x=>`<div class="sourceLevel"><h2>${esc(x[0])}</h2><p>${esc(x[1])}</p></div>`).join('')}</div><div class="policyGrid">${policies.map((x,i)=>`<article class="policyCard"><span>0${i+1}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}</div><div class="sourceLinks">${sourceLinks.map(x=>`<a class="sourceLink" href="${x[2]}" target="_blank" rel="noopener"><div><strong>${esc(x[0])}</strong><small> · ${esc(x[1])}</small></div><b>↗</b></a>`).join('')}</div><div class="transparencyBox"><div><strong>${l==='zh-hans'?'数据库覆盖状态':l==='ja'?'データベース収載状況':'Database coverage'}</strong><p>${l==='zh-hans'?'当前公开的是经过产品级核验的精选记录，不宣称覆盖日本全部医药品。覆盖范围会在官方资料核验完成后逐步扩大。':l==='ja'?'現在公開しているのは製品別に確認した選定記録であり、日本の全医薬品を網羅しているとは表明しません。':'The public database is a curated set of product-level verified records. It does not claim complete coverage of all medicines in Japan.'}</p></div><div><strong>${l==='zh-hans'?'医疗审阅声明':l==='ja'?'医療レビューに関する表示':'Medical-review disclosure'}</strong><p>${l==='zh-hans'?'除非页面明确标注具名审阅者，否则不要把 TOKYO MEDI 的编辑核验理解为医生或药师对个体医疗问题的审阅。':l==='ja'?'ページに記名の医療専門家レビューが明示されない限り、編集上の確認を個別医療判断のレビューとはみなしません。':'Unless a named licensed reviewer is explicitly shown, editorial verification should not be interpreted as clinician review of an individual medical question.'}</p></div></div></div></section></main>`;
 const ld=breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.sources,p(l,'sources')]]);
 return shell(l,req,t.nav.sources,intro,'sources',body,ld);
}

export function aboutPage(l,req){const t=UI[l],title=l==='zh-hans'?'关于 TOKYO MEDI':l==='ja'?'TOKYO MEDIについて':'About TOKYO MEDI',desc=l==='zh-hans'?'面向国际用户整理日本医药品资料、官方来源、医疗指南与赴日就医信息。':l==='ja'?'海外利用者向けに、日本の医薬品資料、一次情報、医療ガイド、日本での受診情報を整理しています。':'A reference platform organizing Japanese medicine information, primary sources, medical guides and care-in-Japan information for international users.';
 const boundaries=l==='zh-hans'?[
   ['资料范围','整理日本商品名、一般名、制造销售企业、规格、官方资料和国际患者受理信息。'],
   ['医疗边界','TOKYO MEDI 不提供诊断、处方或个体化治疗建议。相关判断由医生、药师等专业人员完成。'],
   ['处方药信息','处方药页面提供资料与流程入口；实际使用与取得须经过相应医疗和合规流程。'],
   ['联系与更正','一般联系及资料更正：'+EMAIL]
 ]:l==='ja'?[
   ['掲載情報','日本販売名、一般名、製造販売元、規格、一次資料、海外患者の受入情報を整理します。'],
   ['医療上の範囲','TOKYO MEDI は診断、処方、個別の治療助言を行いません。これらの判断は医師・薬剤師等の専門家が行います。'],
   ['処方薬情報','処方薬ページは資料と手続きの案内を目的とし、実際の使用・入手には適切な医療・法令上の手続きが必要です。'],
   ['連絡・訂正','一般連絡・資料訂正：'+EMAIL]
 ]:[
   ['Information covered','Japanese product names, generics, marketing authorization holders, strengths, primary sources and international-patient intake information.'],
   ['Medical scope','TOKYO MEDI does not provide diagnosis, prescriptions or individualized treatment advice. These decisions belong to licensed clinicians and pharmacists.'],
   ['Prescription medicine information','Prescription pages provide reference information and process guidance; actual use and access require the relevant clinical and regulatory process.'],
   ['Contact & corrections','General contact and data corrections: '+EMAIL]
 ];
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">ABOUT / TRANSPARENCY</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div></section><section class="content"><div class="wrap"><div class="aboutBoundary">${boundaries.map((x,i)=>`<article><span>0${i+1}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p></article>`).join('')}</div><div class="strengthList">${strengths.map((s,i)=>`<div class="strengthRow"><span>0${i+1}</span><h3>${esc(s.title[l]||s.title.en)}</h3><p>${esc(s.body[l]||s.body.en)}</p></div>`).join('')}</div><div class="rxNote">${esc(t.rxNotice)}</div></div></section></main>`;
 const ld=jsonLd({'@context':'https://schema.org','@type':'AboutPage',name:title,description:desc,url:SITE+p(l,'about'),inLanguage:htmlLang(l),about:{'@id':SITE+'/#organization'}})+breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[title,p(l,'about')]]);
 return shell(l,req,title,desc,'about',body,ld);
}

export function inquiryPage(l,req){const t=UI[l],u=new URL(req.url),medicine=(u.searchParams.get('medicine')||'').slice(0,200); const title=t.institution; const intro=t.institutionDesc; const labels=l==='zh-hans'?['机构名称','国家 / 地区','药品 / 品项','预计数量','公开的许可登记信息（可选）','其他说明']:l==='ja'?['機関名','国・地域','医薬品・品目','数量','公開されている許可登録情報（任意）','その他']:['Institution','Country / region','Medicine / item','Estimated quantity','Public licence reference (optional)','Notes'];
 const notice=l==='zh-hans'?'本页仅用于医疗机构、药局与企业的医药品询价。TOKYO MEDI 不提供个人医疗咨询、挂号、诊断、处方或就医协调，也不接受个人处方药购买请求。':l==='ja'?'本ページは医療機関・薬局・企業からの医薬品照会専用です。個人向けの医療相談、予約、診断、処方、受診調整、処方薬購入依頼は受け付けていません。':'This page is only for medicine inquiries from institutions, pharmacies and companies. TOKYO MEDI does not provide personal medical consultation, appointments, diagnosis, prescribing or care coordination, and does not accept personal prescription-medicine purchase requests.';
 const body=`<main><section class="pageHero"><div class="wrap"><div class="eyebrow">INSTITUTIONAL INQUIRY</div><h1>${esc(title)}</h1><p>${esc(intro)}</p></div></section><section class="content"><div class="wrap detailGrid"><div><div class="rxNote institutionOnlyNotice">${esc(notice)}</div><form id="inquiryForm" class="formGrid" onsubmit="return buildInquiry(event)">${labels.map((lab,i)=>`<div class="field ${i>=3?'full':''}"><label for="f${i}">${esc(lab)}</label>${i>=3?`<textarea id="f${i}" name="f${i}"></textarea>`:`<input id="f${i}" name="f${i}" value="${i===2?esc(medicine):''}">`}</div>`).join('')}<div class="field full"><button class="btn teal" type="submit">${l==='zh-hans'?'整理询价邮件':l==='ja'?'照会メールを作成':'Prepare inquiry email'}</button><p class="formNote">${l==='zh-hans'?'仅填写必要的机构与品项信息；不要通过普通电子邮件发送患者资料、密码、证件扫描件或保密资质文件。':l==='ja'?'必要な機関情報と品目情報のみ記載し、患者情報、パスワード、身分証の画像、機密の許可書類は通常のメールで送信しないでください。':'Include only the institution and item details needed. Do not email patient records, passwords, ID scans or confidential licence documents.'}</p></div></form><div id="generated" class="generated"></div></div><aside class="sideNote"><strong>B2B / INSTITUTIONAL</strong><p>${esc(notice)}</p><a class="btn ghost" href="mailto:${EMAIL}">${EMAIL}</a></aside></div></section></main><script>function buildInquiry(e){e.preventDefault();const f=new FormData(e.target);const labs=${JSON.stringify(labels)};const lines=labs.map((x,i)=>x+': '+(f.get('f'+i)||'-'));const type=${JSON.stringify(title)};const text='TOKYO MEDI - '+type+'\\n\\n'+lines.join('\\n');const box=document.getElementById('generated');box.style.display='block';box.textContent=text+'\\n\\nEmail: ${EMAIL}';const a=document.createElement('a');a.className='btn teal';a.style.marginTop='14px';a.textContent=${JSON.stringify(l==='zh-hans'?'打开邮件':l==='ja'?'メールを開く':'Open email')};a.href='mailto:${EMAIL}?subject='+encodeURIComponent('TOKYO MEDI - '+type)+'&body='+encodeURIComponent(text);box.appendChild(document.createElement('br'));box.appendChild(a);return false}</script>`; const ld=breadcrumbLd(l,[[l==='zh-hans'?'首页':l==='ja'?'ホーム':'Home',p(l)],[t.nav.inquiry,p(l,'inquiry')]]); return shell(l,req,title,intro,'inquiry',body,ld);}
